// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/proto/login/code.proto

package login

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendCodeRequest struct {
	// 区号
	NationCode string `protobuf:"bytes,1,opt,name=nationCode,proto3" json:"nationCode,omitempty"`
	// 电话
	Telephone string `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	// 发送类型,call ,sms
	SendType string `protobuf:"bytes,3,opt,name=sendType,proto3" json:"sendType,omitempty"`
	// ip
	Ip string `protobuf:"bytes,4,opt,name=ip,proto3" json:"ip,omitempty"`
	// 模板
	Template             string   `protobuf:"bytes,5,opt,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendCodeRequest) Reset()         { *m = SendCodeRequest{} }
func (m *SendCodeRequest) String() string { return proto.CompactTextString(m) }
func (*SendCodeRequest) ProtoMessage()    {}
func (*SendCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{0}
}

func (m *SendCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCodeRequest.Unmarshal(m, b)
}
func (m *SendCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCodeRequest.Marshal(b, m, deterministic)
}
func (m *SendCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCodeRequest.Merge(m, src)
}
func (m *SendCodeRequest) XXX_Size() int {
	return xxx_messageInfo_SendCodeRequest.Size(m)
}
func (m *SendCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendCodeRequest proto.InternalMessageInfo

func (m *SendCodeRequest) GetNationCode() string {
	if m != nil {
		return m.NationCode
	}
	return ""
}

func (m *SendCodeRequest) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *SendCodeRequest) GetSendType() string {
	if m != nil {
		return m.SendType
	}
	return ""
}

func (m *SendCodeRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *SendCodeRequest) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

type SendCodeResponse struct {
	// code
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// msg
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 时间戳
	NowTime int64 `protobuf:"varint,3,opt,name=nowTime,proto3" json:"nowTime,omitempty"`
	// 数据
	Data                 map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *SendCodeResponse) Reset()         { *m = SendCodeResponse{} }
func (m *SendCodeResponse) String() string { return proto.CompactTextString(m) }
func (*SendCodeResponse) ProtoMessage()    {}
func (*SendCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{1}
}

func (m *SendCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendCodeResponse.Unmarshal(m, b)
}
func (m *SendCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendCodeResponse.Marshal(b, m, deterministic)
}
func (m *SendCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendCodeResponse.Merge(m, src)
}
func (m *SendCodeResponse) XXX_Size() int {
	return xxx_messageInfo_SendCodeResponse.Size(m)
}
func (m *SendCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendCodeResponse proto.InternalMessageInfo

func (m *SendCodeResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *SendCodeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *SendCodeResponse) GetNowTime() int64 {
	if m != nil {
		return m.NowTime
	}
	return 0
}

func (m *SendCodeResponse) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type VerifyRequest struct {
	// 区号
	NationCode string `protobuf:"bytes,1,opt,name=nationCode,proto3" json:"nationCode,omitempty"`
	// 手机号
	Telephone string `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	// 验证码
	Code string `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	// 模板
	Template             string   `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyRequest) Reset()         { *m = VerifyRequest{} }
func (m *VerifyRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyRequest) ProtoMessage()    {}
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{2}
}

func (m *VerifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyRequest.Unmarshal(m, b)
}
func (m *VerifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyRequest.Marshal(b, m, deterministic)
}
func (m *VerifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyRequest.Merge(m, src)
}
func (m *VerifyRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyRequest.Size(m)
}
func (m *VerifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyRequest proto.InternalMessageInfo

func (m *VerifyRequest) GetNationCode() string {
	if m != nil {
		return m.NationCode
	}
	return ""
}

func (m *VerifyRequest) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *VerifyRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *VerifyRequest) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

type VerifyResponse struct {
	// code
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// msg
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 时间戳
	NowTime int64 `protobuf:"varint,3,opt,name=nowTime,proto3" json:"nowTime,omitempty"`
	// 数据
	Data                 map[string]string `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VerifyResponse) Reset()         { *m = VerifyResponse{} }
func (m *VerifyResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyResponse) ProtoMessage()    {}
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{3}
}

func (m *VerifyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResponse.Unmarshal(m, b)
}
func (m *VerifyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResponse.Marshal(b, m, deterministic)
}
func (m *VerifyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResponse.Merge(m, src)
}
func (m *VerifyResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyResponse.Size(m)
}
func (m *VerifyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResponse proto.InternalMessageInfo

func (m *VerifyResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VerifyResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *VerifyResponse) GetNowTime() int64 {
	if m != nil {
		return m.NowTime
	}
	return 0
}

func (m *VerifyResponse) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type IsCheckImageCodeRequest struct {
	// 区号
	NationCode string `protobuf:"bytes,1,opt,name=nationCode,proto3" json:"nationCode,omitempty"`
	// 手机号
	Telephone string `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	// 场景
	Scene                string   `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsCheckImageCodeRequest) Reset()         { *m = IsCheckImageCodeRequest{} }
func (m *IsCheckImageCodeRequest) String() string { return proto.CompactTextString(m) }
func (*IsCheckImageCodeRequest) ProtoMessage()    {}
func (*IsCheckImageCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{4}
}

func (m *IsCheckImageCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsCheckImageCodeRequest.Unmarshal(m, b)
}
func (m *IsCheckImageCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsCheckImageCodeRequest.Marshal(b, m, deterministic)
}
func (m *IsCheckImageCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsCheckImageCodeRequest.Merge(m, src)
}
func (m *IsCheckImageCodeRequest) XXX_Size() int {
	return xxx_messageInfo_IsCheckImageCodeRequest.Size(m)
}
func (m *IsCheckImageCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IsCheckImageCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IsCheckImageCodeRequest proto.InternalMessageInfo

func (m *IsCheckImageCodeRequest) GetNationCode() string {
	if m != nil {
		return m.NationCode
	}
	return ""
}

func (m *IsCheckImageCodeRequest) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *IsCheckImageCodeRequest) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

type IsCheckImageCodeResponse struct {
	// code
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// msg
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 时间戳
	NowTime int64 `protobuf:"varint,3,opt,name=nowTime,proto3" json:"nowTime,omitempty"`
	// 数据
	Data                 bool     `protobuf:"varint,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IsCheckImageCodeResponse) Reset()         { *m = IsCheckImageCodeResponse{} }
func (m *IsCheckImageCodeResponse) String() string { return proto.CompactTextString(m) }
func (*IsCheckImageCodeResponse) ProtoMessage()    {}
func (*IsCheckImageCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{5}
}

func (m *IsCheckImageCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsCheckImageCodeResponse.Unmarshal(m, b)
}
func (m *IsCheckImageCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsCheckImageCodeResponse.Marshal(b, m, deterministic)
}
func (m *IsCheckImageCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsCheckImageCodeResponse.Merge(m, src)
}
func (m *IsCheckImageCodeResponse) XXX_Size() int {
	return xxx_messageInfo_IsCheckImageCodeResponse.Size(m)
}
func (m *IsCheckImageCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_IsCheckImageCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_IsCheckImageCodeResponse proto.InternalMessageInfo

func (m *IsCheckImageCodeResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *IsCheckImageCodeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *IsCheckImageCodeResponse) GetNowTime() int64 {
	if m != nil {
		return m.NowTime
	}
	return 0
}

func (m *IsCheckImageCodeResponse) GetData() bool {
	if m != nil {
		return m.Data
	}
	return false
}

type VerifyImageCodeRequest struct {
	// 区号
	NationCode string `protobuf:"bytes,1,opt,name=nationCode,proto3" json:"nationCode,omitempty"`
	// 手机号
	Telephone string `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	// 图形验证码ticket
	Ticket string `protobuf:"bytes,3,opt,name=ticket,proto3" json:"ticket,omitempty"`
	// 图形验证码randStr
	RandStr string `protobuf:"bytes,4,opt,name=randStr,proto3" json:"randStr,omitempty"`
	// 图形验证码ip
	Ip string `protobuf:"bytes,5,opt,name=ip,proto3" json:"ip,omitempty"`
	// 场景
	Scene                string   `protobuf:"bytes,6,opt,name=scene,proto3" json:"scene,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyImageCodeRequest) Reset()         { *m = VerifyImageCodeRequest{} }
func (m *VerifyImageCodeRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyImageCodeRequest) ProtoMessage()    {}
func (*VerifyImageCodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{6}
}

func (m *VerifyImageCodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyImageCodeRequest.Unmarshal(m, b)
}
func (m *VerifyImageCodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyImageCodeRequest.Marshal(b, m, deterministic)
}
func (m *VerifyImageCodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyImageCodeRequest.Merge(m, src)
}
func (m *VerifyImageCodeRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyImageCodeRequest.Size(m)
}
func (m *VerifyImageCodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyImageCodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyImageCodeRequest proto.InternalMessageInfo

func (m *VerifyImageCodeRequest) GetNationCode() string {
	if m != nil {
		return m.NationCode
	}
	return ""
}

func (m *VerifyImageCodeRequest) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *VerifyImageCodeRequest) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

func (m *VerifyImageCodeRequest) GetRandStr() string {
	if m != nil {
		return m.RandStr
	}
	return ""
}

func (m *VerifyImageCodeRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *VerifyImageCodeRequest) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

type VerifyImageCodeResponse struct {
	// code
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// msg
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 时间戳
	NowTime              int64    `protobuf:"varint,3,opt,name=nowTime,proto3" json:"nowTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyImageCodeResponse) Reset()         { *m = VerifyImageCodeResponse{} }
func (m *VerifyImageCodeResponse) String() string { return proto.CompactTextString(m) }
func (*VerifyImageCodeResponse) ProtoMessage()    {}
func (*VerifyImageCodeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{7}
}

func (m *VerifyImageCodeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyImageCodeResponse.Unmarshal(m, b)
}
func (m *VerifyImageCodeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyImageCodeResponse.Marshal(b, m, deterministic)
}
func (m *VerifyImageCodeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyImageCodeResponse.Merge(m, src)
}
func (m *VerifyImageCodeResponse) XXX_Size() int {
	return xxx_messageInfo_VerifyImageCodeResponse.Size(m)
}
func (m *VerifyImageCodeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyImageCodeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyImageCodeResponse proto.InternalMessageInfo

func (m *VerifyImageCodeResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *VerifyImageCodeResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *VerifyImageCodeResponse) GetNowTime() int64 {
	if m != nil {
		return m.NowTime
	}
	return 0
}

type GetSendStatusRequest struct {
	// 区号
	NationCode string `protobuf:"bytes,1,opt,name=nationCode,proto3" json:"nationCode,omitempty"`
	// 手机号
	Telephone string `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	// 发送类型
	SendType string `protobuf:"bytes,3,opt,name=sendType,proto3" json:"sendType,omitempty"`
	// 模板
	Template string `protobuf:"bytes,4,opt,name=template,proto3" json:"template,omitempty"`
	// 是否越狱标示
	SignR int64 `protobuf:"varint,5,opt,name=signR,proto3" json:"signR,omitempty"`
	// ip
	Ip                   string   `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetSendStatusRequest) Reset()         { *m = GetSendStatusRequest{} }
func (m *GetSendStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetSendStatusRequest) ProtoMessage()    {}
func (*GetSendStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{8}
}

func (m *GetSendStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSendStatusRequest.Unmarshal(m, b)
}
func (m *GetSendStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSendStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetSendStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSendStatusRequest.Merge(m, src)
}
func (m *GetSendStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetSendStatusRequest.Size(m)
}
func (m *GetSendStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSendStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetSendStatusRequest proto.InternalMessageInfo

func (m *GetSendStatusRequest) GetNationCode() string {
	if m != nil {
		return m.NationCode
	}
	return ""
}

func (m *GetSendStatusRequest) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *GetSendStatusRequest) GetSendType() string {
	if m != nil {
		return m.SendType
	}
	return ""
}

func (m *GetSendStatusRequest) GetTemplate() string {
	if m != nil {
		return m.Template
	}
	return ""
}

func (m *GetSendStatusRequest) GetSignR() int64 {
	if m != nil {
		return m.SignR
	}
	return 0
}

func (m *GetSendStatusRequest) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type GetSendStatusResponse struct {
	// code
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// msg
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 时间戳
	NowTime int64 `protobuf:"varint,3,opt,name=nowTime,proto3" json:"nowTime,omitempty"`
	// 数据
	Data                 *SendStatus `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetSendStatusResponse) Reset()         { *m = GetSendStatusResponse{} }
func (m *GetSendStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetSendStatusResponse) ProtoMessage()    {}
func (*GetSendStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{9}
}

func (m *GetSendStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetSendStatusResponse.Unmarshal(m, b)
}
func (m *GetSendStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetSendStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetSendStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetSendStatusResponse.Merge(m, src)
}
func (m *GetSendStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetSendStatusResponse.Size(m)
}
func (m *GetSendStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetSendStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetSendStatusResponse proto.InternalMessageInfo

func (m *GetSendStatusResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *GetSendStatusResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *GetSendStatusResponse) GetNowTime() int64 {
	if m != nil {
		return m.NowTime
	}
	return 0
}

func (m *GetSendStatusResponse) GetData() *SendStatus {
	if m != nil {
		return m.Data
	}
	return nil
}

type SendStatus struct {
	// 需要图形验证码
	NeedImageCode bool `protobuf:"varint,1,opt,name=needImageCode,proto3" json:"needImageCode,omitempty"`
	// 强制语音
	ForceCall bool `protobuf:"varint,2,opt,name=forceCall,proto3" json:"forceCall,omitempty"`
	// 被禁止
	IsForbidden bool `protobuf:"varint,3,opt,name=isForbidden,proto3" json:"isForbidden,omitempty"`
	// 数量超限制
	NumberLimit          bool     `protobuf:"varint,4,opt,name=numberLimit,proto3" json:"numberLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendStatus) Reset()         { *m = SendStatus{} }
func (m *SendStatus) String() string { return proto.CompactTextString(m) }
func (*SendStatus) ProtoMessage()    {}
func (*SendStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_97ec12a11ad2dae9, []int{10}
}

func (m *SendStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendStatus.Unmarshal(m, b)
}
func (m *SendStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendStatus.Marshal(b, m, deterministic)
}
func (m *SendStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendStatus.Merge(m, src)
}
func (m *SendStatus) XXX_Size() int {
	return xxx_messageInfo_SendStatus.Size(m)
}
func (m *SendStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SendStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SendStatus proto.InternalMessageInfo

func (m *SendStatus) GetNeedImageCode() bool {
	if m != nil {
		return m.NeedImageCode
	}
	return false
}

func (m *SendStatus) GetForceCall() bool {
	if m != nil {
		return m.ForceCall
	}
	return false
}

func (m *SendStatus) GetIsForbidden() bool {
	if m != nil {
		return m.IsForbidden
	}
	return false
}

func (m *SendStatus) GetNumberLimit() bool {
	if m != nil {
		return m.NumberLimit
	}
	return false
}

func init() {
	proto.RegisterType((*SendCodeRequest)(nil), "login.SendCodeRequest")
	proto.RegisterType((*SendCodeResponse)(nil), "login.SendCodeResponse")
	proto.RegisterMapType((map[string]string)(nil), "login.SendCodeResponse.DataEntry")
	proto.RegisterType((*VerifyRequest)(nil), "login.VerifyRequest")
	proto.RegisterType((*VerifyResponse)(nil), "login.VerifyResponse")
	proto.RegisterMapType((map[string]string)(nil), "login.VerifyResponse.DataEntry")
	proto.RegisterType((*IsCheckImageCodeRequest)(nil), "login.IsCheckImageCodeRequest")
	proto.RegisterType((*IsCheckImageCodeResponse)(nil), "login.IsCheckImageCodeResponse")
	proto.RegisterType((*VerifyImageCodeRequest)(nil), "login.VerifyImageCodeRequest")
	proto.RegisterType((*VerifyImageCodeResponse)(nil), "login.VerifyImageCodeResponse")
	proto.RegisterType((*GetSendStatusRequest)(nil), "login.GetSendStatusRequest")
	proto.RegisterType((*GetSendStatusResponse)(nil), "login.GetSendStatusResponse")
	proto.RegisterType((*SendStatus)(nil), "login.SendStatus")
}

func init() {
	proto.RegisterFile("examples/proto/login/code.proto", fileDescriptor_97ec12a11ad2dae9)
}

var fileDescriptor_97ec12a11ad2dae9 = []byte{
	// 874 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0x97, 0xf3, 0x6f, 0xd3, 0x57, 0xba, 0x6d, 0x47, 0xdd, 0x36, 0x1b, 0x42, 0x67, 0xd7, 0x68,
	0x45, 0x59, 0x94, 0x58, 0x94, 0xc3, 0xa2, 0x4a, 0x08, 0x29, 0xe5, 0x8f, 0x56, 0xe2, 0x34, 0x5d,
	0x71, 0xe2, 0xe2, 0xc4, 0x53, 0x77, 0xd4, 0x78, 0xc6, 0x6b, 0x4f, 0x16, 0x72, 0x41, 0x88, 0xaf,
	0xc0, 0x01, 0xbe, 0x01, 0x7c, 0x00, 0xbe, 0x09, 0x17, 0xc4, 0xc1, 0x27, 0x0e, 0xc8, 0xe2, 0x0b,
	0x70, 0x43, 0xf3, 0xc7, 0x8e, 0xe3, 0x34, 0x88, 0x0b, 0x11, 0x17, 0xfb, 0xcd, 0x6f, 0xde, 0xbc,
	0x7f, 0x3f, 0xcf, 0x7b, 0x06, 0x4c, 0xbf, 0xf2, 0xa3, 0x78, 0x46, 0x53, 0x2f, 0x4e, 0x84, 0x14,
	0xde, 0x4c, 0x84, 0x8c, 0x7b, 0x53, 0x11, 0xd0, 0x91, 0x06, 0x50, 0x5b, 0x23, 0xfd, 0x61, 0xc8,
	0xe4, 0xcd, 0x7c, 0x32, 0x9a, 0x8a, 0xc8, 0x0b, 0x45, 0x28, 0x8c, 0xfa, 0x64, 0x7e, 0xad, 0x57,
	0xe6, 0xac, 0x92, 0xcc, 0xa9, 0xfe, 0x20, 0x14, 0x22, 0x9c, 0x51, 0xcf, 0x8f, 0x99, 0xe7, 0x73,
	0x2e, 0xa4, 0x2f, 0x99, 0xe0, 0xa9, 0xd9, 0x75, 0x7f, 0x73, 0x60, 0xff, 0x8a, 0xf2, 0xe0, 0x52,
	0x04, 0x94, 0xd0, 0x97, 0x73, 0x9a, 0x4a, 0x34, 0x02, 0xe0, 0x5a, 0x49, 0x81, 0x3d, 0xe7, 0x91,
	0x73, 0xb6, 0x33, 0xbe, 0x9f, 0x67, 0xb8, 0x82, 0x92, 0x8a, 0x8c, 0xde, 0x81, 0x1d, 0x49, 0x67,
	0x34, 0xbe, 0x11, 0x9c, 0xf6, 0x1a, 0x5a, 0x7d, 0x2f, 0xcf, 0xf0, 0x12, 0x24, 0x4b, 0x11, 0x9d,
	0x41, 0x37, 0xa5, 0x3c, 0x78, 0xb1, 0x88, 0x69, 0xaf, 0xa9, 0x75, 0x5f, 0xcb, 0x33, 0x5c, 0x62,
	0xa4, 0x94, 0xd0, 0x31, 0x34, 0x58, 0xdc, 0x6b, 0x69, 0x9d, 0x4e, 0x9e, 0xe1, 0x06, 0x8b, 0x49,
	0x83, 0xc5, 0xca, 0x82, 0xa4, 0x51, 0x3c, 0xf3, 0x25, 0xed, 0xb5, 0x97, 0x16, 0x0a, 0x8c, 0x94,
	0x92, 0xfb, 0xa7, 0x03, 0x07, 0xcb, 0xe4, 0xd2, 0x58, 0xf0, 0x94, 0xa2, 0x01, 0xb4, 0xa6, 0x45,
	0x5e, 0xcd, 0x71, 0x37, 0xcf, 0xb0, 0x5e, 0x13, 0xfd, 0x44, 0x0f, 0xa1, 0x19, 0xa5, 0xa1, 0xcd,
	0xe2, 0x5e, 0x9e, 0x61, 0xb5, 0x24, 0xea, 0x81, 0x9e, 0xc0, 0x3d, 0x2e, 0xbe, 0x7c, 0xc1, 0x22,
	0x13, 0x78, 0x73, 0xbc, 0x9b, 0x67, 0xb8, 0x80, 0x48, 0x21, 0xa0, 0x0f, 0xa1, 0x15, 0xf8, 0xd2,
	0xef, 0xb5, 0x1e, 0x35, 0xcf, 0x76, 0xcf, 0x1f, 0x8f, 0x34, 0x69, 0xa3, 0x7a, 0x18, 0xa3, 0x8f,
	0x7c, 0xe9, 0x7f, 0xcc, 0x65, 0xb2, 0x30, 0x21, 0xa8, 0x23, 0x44, 0x3f, 0xfb, 0xcf, 0x60, 0xa7,
	0xdc, 0x44, 0x07, 0xd0, 0xbc, 0xa5, 0x0b, 0x43, 0x02, 0x51, 0x22, 0x3a, 0x82, 0xf6, 0x2b, 0x7f,
	0x36, 0xb7, 0x95, 0x26, 0x66, 0x71, 0xd1, 0x78, 0xdf, 0x71, 0x7f, 0x76, 0x60, 0xef, 0x73, 0x9a,
	0xb0, 0xeb, 0xc5, 0x56, 0x98, 0x2c, 0x0a, 0x69, 0x58, 0xac, 0x17, 0xb2, 0xca, 0x52, 0xeb, 0x1f,
	0x59, 0xfa, 0xc3, 0x81, 0xfb, 0x45, 0xd8, 0x5b, 0xe2, 0xe8, 0x83, 0x15, 0x8e, 0xb0, 0xe5, 0x68,
	0x35, 0x88, 0xff, 0x82, 0xa1, 0xef, 0x1d, 0x38, 0x79, 0x9e, 0x5e, 0xde, 0xd0, 0xe9, 0xed, 0xf3,
	0xc8, 0x0f, 0xe9, 0xd6, 0x6e, 0x1d, 0x86, 0x76, 0x3a, 0xa5, 0xbc, 0x20, 0x6b, 0x27, 0xcf, 0xb0,
	0x01, 0x88, 0x79, 0xb9, 0x3f, 0x38, 0xd0, 0x5b, 0x8f, 0x6c, 0x4b, 0x74, 0x0c, 0x4a, 0x3a, 0x9c,
	0xb3, 0x6e, 0xbd, 0xda, 0xee, 0x5f, 0x0e, 0x1c, 0x1b, 0x6a, 0xb6, 0x5b, 0x33, 0x17, 0x3a, 0x92,
	0x4d, 0x6f, 0xa9, 0xb4, 0x45, 0x83, 0x3c, 0xc3, 0x16, 0x21, 0xf6, 0xad, 0x12, 0x4c, 0x7c, 0x1e,
	0x5c, 0xc9, 0xc4, 0x7e, 0xe4, 0x3a, 0x41, 0x0b, 0x91, 0x42, 0xb0, 0xad, 0xac, 0xbd, 0xd6, 0xca,
	0x4a, 0x5a, 0x3a, 0x1b, 0x68, 0x59, 0xc0, 0xc9, 0x5a, 0xea, 0xdb, 0x21, 0xc5, 0xfd, 0xa6, 0x01,
	0x47, 0x9f, 0x52, 0xa9, 0x1a, 0xd7, 0x95, 0xf4, 0xe5, 0x3c, 0xfd, 0x9f, 0x8d, 0x87, 0x7f, 0xdd,
	0x60, 0x74, 0x95, 0x59, 0xc8, 0x89, 0x26, 0xa0, 0x69, 0xab, 0xac, 0x00, 0x62, 0x5e, 0x96, 0x9e,
	0x4e, 0x9d, 0x1e, 0xf7, 0x27, 0x07, 0x1e, 0xd4, 0x4a, 0xb0, 0xa5, 0x1b, 0xe1, 0x55, 0x6e, 0xc4,
	0xee, 0xf9, 0x61, 0x65, 0x88, 0x98, 0x40, 0xd6, 0x2e, 0xc9, 0xaf, 0x0e, 0xc0, 0x72, 0x1b, 0x3d,
	0x83, 0x3d, 0x4e, 0x69, 0x50, 0x7e, 0x35, 0x3a, 0xd0, 0xee, 0xf8, 0x30, 0xcf, 0xf0, 0xea, 0x06,
	0x59, 0x5d, 0x2a, 0xb2, 0xae, 0x45, 0x32, 0xa5, 0x97, 0xfe, 0x6c, 0xa6, 0x13, 0xe8, 0x1a, 0xb2,
	0x4a, 0x90, 0x2c, 0x45, 0xf4, 0x2e, 0xec, 0xb2, 0xf4, 0x13, 0x91, 0x4c, 0x58, 0x10, 0x50, 0xae,
	0x13, 0xea, 0x8e, 0xf7, 0xf3, 0x0c, 0x57, 0x61, 0x52, 0x5d, 0xa8, 0x23, 0x7c, 0x1e, 0x4d, 0x68,
	0xf2, 0x19, 0x8b, 0x98, 0xb4, 0x37, 0x5e, 0x1f, 0xa9, 0xc0, 0xa4, 0xba, 0x38, 0xff, 0xb1, 0x05,
	0x2d, 0x1d, 0xdb, 0x17, 0xd0, 0x2d, 0xc6, 0x28, 0x3a, 0x5e, 0x9b, 0xab, 0xfa, 0xe3, 0xec, 0x9f,
	0x6c, 0x98, 0xb7, 0x2e, 0xfe, 0xf6, 0x97, 0xdf, 0xbf, 0x6b, 0x3c, 0x74, 0x8f, 0xbc, 0x79, 0x4a,
	0x13, 0xfd, 0x5b, 0xe5, 0xa9, 0x6f, 0x69, 0xa8, 0xa4, 0x0b, 0xe7, 0x29, 0xba, 0x82, 0x8e, 0xb9,
	0x6a, 0xe8, 0xa8, 0x36, 0x0f, 0x8c, 0xe5, 0x07, 0x77, 0x4e, 0x09, 0x77, 0xa0, 0xed, 0x1e, 0xbb,
	0x87, 0x15, 0xbb, 0xaf, 0xb4, 0x8a, 0x32, 0xfa, 0x35, 0x1c, 0xd4, 0xbb, 0x2a, 0x3a, 0xb5, 0x86,
	0x36, 0x0c, 0x82, 0x3e, 0xde, 0xb8, 0x6f, 0x5d, 0xbe, 0xad, 0x5d, 0xbe, 0xe9, 0x9e, 0x56, 0x5c,
	0xb2, 0x74, 0x38, 0x55, 0xda, 0x43, 0xa6, 0xd4, 0xcb, 0xa4, 0x16, 0xb0, 0x5f, 0xeb, 0x1f, 0xe8,
	0x8d, 0x95, 0x3c, 0xd6, 0xbc, 0x9f, 0x6e, 0xda, 0xb6, 0xce, 0xdf, 0xd2, 0xce, 0x1f, 0xbb, 0x83,
	0xb5, 0x7c, 0x6b, 0xae, 0x5f, 0xc2, 0xde, 0xca, 0xdd, 0x41, 0xaf, 0x5b, 0xcb, 0x77, 0x35, 0x95,
	0xfe, 0xe0, 0xee, 0x4d, 0xeb, 0xf4, 0x89, 0x76, 0x8a, 0xdd, 0x7e, 0xc5, 0x69, 0x48, 0xe5, 0x50,
	0x13, 0x98, 0x6a, 0xdd, 0x0b, 0xe7, 0xe9, 0xa4, 0xa3, 0xff, 0x69, 0xdf, 0xfb, 0x3b, 0x00, 0x00,
	0xff, 0xff, 0xb2, 0x6c, 0x4f, 0x28, 0x4a, 0x0b, 0x00, 0x00,
}
