// Code generated by protoc-gen-go. DO NOT EDIT.
// source: examples/proto/login/login.proto

// 统一登录入口

package login

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthenticateRequest struct {
	// 凭证,cookie:string or token:sting
	Credentials          map[string]string `protobuf:"bytes,1,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *AuthenticateRequest) Reset()         { *m = AuthenticateRequest{} }
func (m *AuthenticateRequest) String() string { return proto.CompactTextString(m) }
func (*AuthenticateRequest) ProtoMessage()    {}
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7218626161720dd5, []int{0}
}

func (m *AuthenticateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateRequest.Unmarshal(m, b)
}
func (m *AuthenticateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateRequest.Marshal(b, m, deterministic)
}
func (m *AuthenticateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateRequest.Merge(m, src)
}
func (m *AuthenticateRequest) XXX_Size() int {
	return xxx_messageInfo_AuthenticateRequest.Size(m)
}
func (m *AuthenticateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateRequest proto.InternalMessageInfo

func (m *AuthenticateRequest) GetCredentials() map[string]string {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type AuthenticateResponse struct {
	// 错误码,0 为正常
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误信息
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 请求响应时间戳
	NowTime int64 `protobuf:"varint,3,opt,name=nowTime,proto3" json:"nowTime,omitempty"`
	// 数据
	Data                 *Data    `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthenticateResponse) Reset()         { *m = AuthenticateResponse{} }
func (m *AuthenticateResponse) String() string { return proto.CompactTextString(m) }
func (*AuthenticateResponse) ProtoMessage()    {}
func (*AuthenticateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7218626161720dd5, []int{1}
}

func (m *AuthenticateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthenticateResponse.Unmarshal(m, b)
}
func (m *AuthenticateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthenticateResponse.Marshal(b, m, deterministic)
}
func (m *AuthenticateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthenticateResponse.Merge(m, src)
}
func (m *AuthenticateResponse) XXX_Size() int {
	return xxx_messageInfo_AuthenticateResponse.Size(m)
}
func (m *AuthenticateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthenticateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthenticateResponse proto.InternalMessageInfo

func (m *AuthenticateResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AuthenticateResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *AuthenticateResponse) GetNowTime() int64 {
	if m != nil {
		return m.NowTime
	}
	return 0
}

func (m *AuthenticateResponse) GetData() *Data {
	if m != nil {
		return m.Data
	}
	return nil
}

type Data struct {
	// userinfoId
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// uri
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// 个人昵称,没有店铺昵称覆盖逻辑
	Nickname string `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// 个人头像,没有店铺头像覆盖逻辑
	HeadImgUrl string `protobuf:"bytes,4,opt,name=headImgUrl,proto3" json:"headImgUrl,omitempty"`
	// 签名
	Signature string `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	// 性别, 性别 0未知,1男,2女
	Sex int64 `protobuf:"varint,6,opt,name=sex,proto3" json:"sex,omitempty"`
	// 区域
	Region string `protobuf:"bytes,7,opt,name=region,proto3" json:"region,omitempty"`
	// 国家
	Country string `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	// 省市
	Province string `protobuf:"bytes,9,opt,name=province,proto3" json:"province,omitempty"`
	// 城市
	City string `protobuf:"bytes,10,opt,name=city,proto3" json:"city,omitempty"`
	// 语言类型,默认 ""
	Lang string `protobuf:"bytes,11,opt,name=lang,proto3" json:"lang,omitempty"`
	// 注册时间戳
	CreateTime int64 `protobuf:"varint,12,opt,name=createTime,proto3" json:"createTime,omitempty"`
	// 更新时间戳
	ModifyTime int64 `protobuf:"varint,13,opt,name=modifyTime,proto3" json:"modifyTime,omitempty"`
	// 当前登录平台id ,对应 center 表 type 字段
	CurrentlyLoggedPlatformId int64    `protobuf:"varint,14,opt,name=currentlyLoggedPlatformId,proto3" json:"currentlyLoggedPlatformId,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_7218626161720dd5, []int{2}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Data) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Data) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *Data) GetHeadImgUrl() string {
	if m != nil {
		return m.HeadImgUrl
	}
	return ""
}

func (m *Data) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

func (m *Data) GetSex() int64 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *Data) GetRegion() string {
	if m != nil {
		return m.Region
	}
	return ""
}

func (m *Data) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Data) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *Data) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Data) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Data) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *Data) GetModifyTime() int64 {
	if m != nil {
		return m.ModifyTime
	}
	return 0
}

func (m *Data) GetCurrentlyLoggedPlatformId() int64 {
	if m != nil {
		return m.CurrentlyLoggedPlatformId
	}
	return 0
}

type LoginRequest struct {
	// 平台id ,对应 center 表 type 字段
	PlatformId int64 `protobuf:"varint,1,opt,name=platformId,proto3" json:"platformId,omitempty"`
	// 登录相关信息,json,手机号登录参数
	// UserType      int64  `json:"userType"`
	//	VerifyType    string `json:"verifyType"`
	//	NationCode    string `json:"nationCode"`
	//	Telephone     string `json:"telephone"`
	//	Code          string `json:"code"`
	//	LoginToken    string `json:"loginToken"`
	//	DeviceId      string `json:"deviceId"`
	//	SysMessageNum int64  `json:"sysMessageNum"`
	Data map[string]string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 凭据类型,普通用户 base, 特权?超级? super
	Scope                string   `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7218626161720dd5, []int{3}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPlatformId() int64 {
	if m != nil {
		return m.PlatformId
	}
	return 0
}

func (m *LoginRequest) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *LoginRequest) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type LoginResponse struct {
	// 错误码,0 为正常
	Code int64 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 错误信息
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// 请求响应时间戳
	NowTime int64 `protobuf:"varint,3,opt,name=nowTime,proto3" json:"nowTime,omitempty"`
	// 数据
	Data                 *Credentials `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7218626161720dd5, []int{4}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginResponse) GetNowTime() int64 {
	if m != nil {
		return m.NowTime
	}
	return 0
}

func (m *LoginResponse) GetData() *Credentials {
	if m != nil {
		return m.Data
	}
	return nil
}

type Credentials struct {
	// userinfoId 对应 bindId
	Uid int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// uri
	Uri string `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	// openid
	Openid string `protobuf:"bytes,3,opt,name=openid,proto3" json:"openid,omitempty"`
	// isNew
	IsNew bool `protobuf:"varint,4,opt,name=isNew,proto3" json:"isNew,omitempty"`
	// 是否首次注册
	IsFirstRegister bool `protobuf:"varint,5,opt,name=isFirstRegister,proto3" json:"isFirstRegister,omitempty"`
	// 是否绑定手机号
	IsBindTelephone bool `protobuf:"varint,6,opt,name=isBindTelephone,proto3" json:"isBindTelephone,omitempty"`
	// platformId
	PlatformInfo         *PlatformInfo `protobuf:"bytes,7,opt,name=platformInfo,proto3" json:"platformInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Credentials) Reset()         { *m = Credentials{} }
func (m *Credentials) String() string { return proto.CompactTextString(m) }
func (*Credentials) ProtoMessage()    {}
func (*Credentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_7218626161720dd5, []int{5}
}

func (m *Credentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Credentials.Unmarshal(m, b)
}
func (m *Credentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Credentials.Marshal(b, m, deterministic)
}
func (m *Credentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Credentials.Merge(m, src)
}
func (m *Credentials) XXX_Size() int {
	return xxx_messageInfo_Credentials.Size(m)
}
func (m *Credentials) XXX_DiscardUnknown() {
	xxx_messageInfo_Credentials.DiscardUnknown(m)
}

var xxx_messageInfo_Credentials proto.InternalMessageInfo

func (m *Credentials) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *Credentials) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Credentials) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *Credentials) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

func (m *Credentials) GetIsFirstRegister() bool {
	if m != nil {
		return m.IsFirstRegister
	}
	return false
}

func (m *Credentials) GetIsBindTelephone() bool {
	if m != nil {
		return m.IsBindTelephone
	}
	return false
}

func (m *Credentials) GetPlatformInfo() *PlatformInfo {
	if m != nil {
		return m.PlatformInfo
	}
	return nil
}

type PlatformInfo struct {
	// platformId
	PlatformId int64 `protobuf:"varint,1,opt,name=platformId,proto3" json:"platformId,omitempty"`
	// originalId 原始ID,platformId 对应的user
	OriginalUid int64 `protobuf:"varint,2,opt,name=originalUid,proto3" json:"originalUid,omitempty"`
	// originalUri 原始uri,platformId 对应的user
	OriginalUri string `protobuf:"bytes,3,opt,name=originalUri,proto3" json:"originalUri,omitempty"`
	// originalOpenid 原始openid,platformId 对应的user
	OriginalOpenid       string   `protobuf:"bytes,4,opt,name=originalOpenid,proto3" json:"originalOpenid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlatformInfo) Reset()         { *m = PlatformInfo{} }
func (m *PlatformInfo) String() string { return proto.CompactTextString(m) }
func (*PlatformInfo) ProtoMessage()    {}
func (*PlatformInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_7218626161720dd5, []int{6}
}

func (m *PlatformInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlatformInfo.Unmarshal(m, b)
}
func (m *PlatformInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlatformInfo.Marshal(b, m, deterministic)
}
func (m *PlatformInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlatformInfo.Merge(m, src)
}
func (m *PlatformInfo) XXX_Size() int {
	return xxx_messageInfo_PlatformInfo.Size(m)
}
func (m *PlatformInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlatformInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlatformInfo proto.InternalMessageInfo

func (m *PlatformInfo) GetPlatformId() int64 {
	if m != nil {
		return m.PlatformId
	}
	return 0
}

func (m *PlatformInfo) GetOriginalUid() int64 {
	if m != nil {
		return m.OriginalUid
	}
	return 0
}

func (m *PlatformInfo) GetOriginalUri() string {
	if m != nil {
		return m.OriginalUri
	}
	return ""
}

func (m *PlatformInfo) GetOriginalOpenid() string {
	if m != nil {
		return m.OriginalOpenid
	}
	return ""
}

func init() {
	proto.RegisterType((*AuthenticateRequest)(nil), "login.AuthenticateRequest")
	proto.RegisterMapType((map[string]string)(nil), "login.AuthenticateRequest.CredentialsEntry")
	proto.RegisterType((*AuthenticateResponse)(nil), "login.AuthenticateResponse")
	proto.RegisterType((*Data)(nil), "login.Data")
	proto.RegisterType((*LoginRequest)(nil), "login.LoginRequest")
	proto.RegisterMapType((map[string]string)(nil), "login.LoginRequest.DataEntry")
	proto.RegisterType((*LoginResponse)(nil), "login.LoginResponse")
	proto.RegisterType((*Credentials)(nil), "login.Credentials")
	proto.RegisterType((*PlatformInfo)(nil), "login.PlatformInfo")
}

func init() {
	proto.RegisterFile("examples/proto/login/login.proto", fileDescriptor_7218626161720dd5)
}

var fileDescriptor_7218626161720dd5 = []byte{
	// 913 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x6e, 0xe4, 0x44,
	0x10, 0x96, 0xe7, 0x27, 0x3b, 0x53, 0x9e, 0x64, 0x43, 0x27, 0x42, 0xde, 0x21, 0x91, 0x47, 0x46,
	0x48, 0x61, 0x57, 0xcc, 0x40, 0x38, 0x80, 0x82, 0x40, 0x62, 0xf8, 0x91, 0x22, 0xad, 0x20, 0x6a,
	0xed, 0x9e, 0x90, 0x90, 0x3a, 0x76, 0x8f, 0xd3, 0x5a, 0x4f, 0xb7, 0x69, 0xb7, 0x77, 0x33, 0x57,
	0x5e, 0x81, 0x27, 0xe0, 0x21, 0x78, 0x06, 0x1e, 0x60, 0x85, 0xc4, 0xc9, 0xe2, 0xc0, 0xc9, 0x4f,
	0x81, 0xba, 0xdb, 0x33, 0xee, 0x19, 0x92, 0xc3, 0x0a, 0x89, 0x4b, 0x75, 0xd5, 0x57, 0x55, 0xdd,
	0xe5, 0xea, 0xfa, 0x6c, 0xc3, 0x84, 0xde, 0x92, 0x65, 0x9e, 0xd1, 0x62, 0x96, 0x4b, 0xa1, 0xc4,
	0x2c, 0x13, 0x29, 0xe3, 0x56, 0x4e, 0x0d, 0x82, 0xfa, 0xc6, 0x18, 0x7f, 0x90, 0x32, 0x75, 0x53,
	0x5e, 0x4f, 0x63, 0xb1, 0x9c, 0xa5, 0x22, 0x15, 0x36, 0xfe, 0xba, 0x5c, 0x18, 0xcb, 0x26, 0x6b,
	0xcd, 0x66, 0x8d, 0x4f, 0x52, 0x21, 0xd2, 0x8c, 0xce, 0x48, 0xce, 0x66, 0x84, 0x73, 0xa1, 0x88,
	0x62, 0x82, 0x17, 0xd6, 0x1b, 0xfd, 0xe6, 0xc1, 0xd1, 0x97, 0xa5, 0xba, 0xa1, 0x5c, 0xb1, 0x98,
	0x28, 0x8a, 0xe9, 0x4f, 0x25, 0x2d, 0x14, 0xfa, 0x11, 0xfc, 0x58, 0xd2, 0x44, 0xc3, 0x24, 0x2b,
	0x02, 0x6f, 0xd2, 0x3d, 0xf3, 0xcf, 0x9f, 0x4c, 0x6d, 0x39, 0x77, 0x24, 0x4c, 0xbf, 0x6a, 0xa3,
	0xbf, 0xe1, 0x4a, 0xae, 0xe6, 0x0f, 0xeb, 0x2a, 0x74, 0xf7, 0xc0, 0xae, 0x31, 0xfe, 0x02, 0x0e,
	0x77, 0x33, 0xd0, 0x21, 0x74, 0x5f, 0xd0, 0x55, 0xe0, 0x4d, 0xbc, 0xb3, 0x21, 0xd6, 0x2a, 0x3a,
	0x86, 0xfe, 0x4b, 0x92, 0x95, 0x34, 0xe8, 0x18, 0xcc, 0x1a, 0x17, 0x9d, 0x4f, 0xbd, 0xe8, 0x57,
	0x0f, 0x8e, 0xb7, 0xcb, 0x28, 0x72, 0xc1, 0x0b, 0x8a, 0x4e, 0xa0, 0x17, 0x8b, 0x84, 0x9a, 0x5d,
	0xba, 0xf3, 0x41, 0x5d, 0x85, 0xc6, 0xc6, 0x46, 0xa2, 0x47, 0xd0, 0x5d, 0x16, 0xa9, 0xdd, 0x6e,
	0xfe, 0xa0, 0xae, 0x42, 0x6d, 0x62, 0x2d, 0xd0, 0x7b, 0xf0, 0x80, 0x8b, 0x57, 0xcf, 0xd8, 0x92,
	0x06, 0x5d, 0x93, 0xeb, 0xd7, 0x55, 0xb8, 0x86, 0xf0, 0x5a, 0x41, 0xef, 0x43, 0x2f, 0x21, 0x8a,
	0x04, 0xbd, 0x89, 0x77, 0xe6, 0x9f, 0xfb, 0x4d, 0x47, 0xbe, 0x26, 0x8a, 0xd8, 0xc3, 0xb4, 0x13,
	0x1b, 0x19, 0xbd, 0xee, 0x41, 0x4f, 0x3b, 0xd0, 0x04, 0xba, 0x25, 0x4b, 0x9a, 0x92, 0x0e, 0xea,
	0x2a, 0x84, 0xb2, 0xa0, 0x92, 0xf1, 0x85, 0xb8, 0x4c, 0xb0, 0x76, 0xe9, 0xba, 0x4a, 0xc9, 0xdc,
	0xba, 0x4a, 0xc9, 0xb0, 0x16, 0xe8, 0x0c, 0x06, 0x9c, 0xc5, 0x2f, 0x38, 0x69, 0x0a, 0x1b, 0xce,
	0x47, 0x75, 0x15, 0x6e, 0x30, 0xbc, 0xd1, 0xd0, 0x14, 0xe0, 0x86, 0x92, 0xe4, 0x72, 0x99, 0x3e,
	0x97, 0x99, 0x29, 0x70, 0x68, 0x4f, 0xd3, 0x28, 0x5b, 0xa6, 0xa5, 0xcc, 0xb0, 0x13, 0x81, 0x9e,
	0xc0, 0xb0, 0x60, 0x29, 0x27, 0xaa, 0x94, 0x34, 0xe8, 0x9b, 0xf0, 0xfd, 0xba, 0x0a, 0x5b, 0x10,
	0xb7, 0xaa, 0xae, 0xb0, 0xa0, 0xb7, 0xc1, 0x9e, 0x79, 0x06, 0x53, 0x61, 0x41, 0x6f, 0xb1, 0x16,
	0x28, 0x82, 0x3d, 0x49, 0x53, 0x26, 0x78, 0xf0, 0xc0, 0x6c, 0x02, 0x75, 0x15, 0x36, 0x08, 0x6e,
	0x56, 0xdd, 0xdd, 0x58, 0x94, 0xfa, 0x9a, 0x83, 0x81, 0x09, 0x32, 0xdd, 0x6d, 0x20, 0xbc, 0x56,
	0xf4, 0xc3, 0xe6, 0x52, 0xbc, 0x64, 0x3c, 0xa6, 0xc1, 0xb0, 0x7d, 0xd8, 0x35, 0x86, 0x37, 0x9a,
	0xb9, 0x67, 0xa6, 0x56, 0x01, 0x98, 0x28, 0x7b, 0xcf, 0x4c, 0xad, 0xb0, 0x91, 0xda, 0x9b, 0x11,
	0x9e, 0x06, 0x7e, 0xeb, 0xd5, 0x36, 0x36, 0x52, 0x37, 0x2a, 0x96, 0x94, 0x28, 0x6a, 0x6e, 0x7b,
	0xd4, 0x5e, 0x4b, 0x8b, 0x62, 0x47, 0xd7, 0xf1, 0x4b, 0x91, 0xb0, 0xc5, 0xca, 0xc4, 0xef, 0xb7,
	0xf1, 0x2d, 0x8a, 0x1d, 0x1d, 0xfd, 0x00, 0x8f, 0xe2, 0x52, 0x4a, 0xca, 0x55, 0xb6, 0x7a, 0x2a,
	0xd2, 0x94, 0x26, 0x57, 0x19, 0x51, 0x0b, 0x21, 0x97, 0x97, 0x49, 0x70, 0x60, 0xd2, 0x4f, 0xeb,
	0x2a, 0xbc, 0x3f, 0x08, 0xdf, 0xef, 0x8a, 0xfe, 0xf0, 0x60, 0xf4, 0x54, 0x0f, 0xdd, 0x9a, 0xaa,
	0x53, 0x80, 0xbc, 0xdd, 0xde, 0x19, 0xb2, 0x16, 0xc5, 0x8e, 0x8e, 0x3e, 0x6b, 0x26, 0xb8, 0x63,
	0x38, 0x7d, 0xda, 0x4c, 0xb0, 0xbb, 0xa5, 0x19, 0x67, 0xcb, 0xe2, 0x9d, 0x99, 0x46, 0x21, 0xf4,
	0x8b, 0x58, 0xe4, 0xeb, 0x51, 0x1c, 0xd6, 0x55, 0x68, 0x01, 0x6c, 0x97, 0xf1, 0x27, 0x30, 0xdc,
	0x64, 0xbf, 0x29, 0xa3, 0xf7, 0x9b, 0x22, 0xfe, 0x27, 0x2a, 0x7f, 0xb8, 0x45, 0x65, 0xd4, 0x34,
	0xc2, 0x79, 0x2d, 0xfd, 0x8b, 0xd1, 0x7f, 0x76, 0xc0, 0x77, 0xfc, 0xff, 0x8d, 0xd8, 0x11, 0xec,
	0x89, 0x9c, 0x72, 0x96, 0x34, 0xbd, 0x34, 0xb4, 0xb1, 0x08, 0x6e, 0x56, 0xdd, 0x6e, 0x56, 0x7c,
	0x47, 0x5f, 0x99, 0x1a, 0x07, 0xb6, 0xdd, 0x06, 0xc0, 0x76, 0x41, 0x9f, 0xc3, 0x43, 0x56, 0x7c,
	0xcb, 0x64, 0xa1, 0x30, 0x4d, 0x59, 0xa1, 0xa8, 0x34, 0x4c, 0x1e, 0xcc, 0x8f, 0xea, 0x2a, 0xdc,
	0x75, 0xe1, 0x5d, 0xc0, 0xa6, 0xcf, 0x19, 0x4f, 0x9e, 0xd1, 0x8c, 0xe6, 0x37, 0x82, 0x53, 0xc3,
	0xf0, 0x4d, 0xfa, 0x96, 0x0b, 0xef, 0x02, 0xe8, 0x12, 0x46, 0x9b, 0xc1, 0xe2, 0x0b, 0x61, 0xf8,
	0xef, 0x9f, 0x1f, 0x35, 0x9d, 0xbc, 0x72, 0x5c, 0xf3, 0xc3, 0xba, 0x0a, 0xb7, 0x82, 0xf1, 0x96,
	0x15, 0xfd, 0xe5, 0xc1, 0xc8, 0x4d, 0x78, 0xe3, 0xb1, 0xfe, 0x08, 0x7c, 0x21, 0x59, 0xca, 0x38,
	0xc9, 0x9e, 0xb3, 0xc4, 0x74, 0xbc, 0x6b, 0x3f, 0x42, 0x0e, 0x8c, 0x5d, 0x63, 0x2b, 0x45, 0xb2,
	0xe6, 0x1a, 0xb6, 0x53, 0x24, 0xc3, 0xae, 0x81, 0x2e, 0xe0, 0x60, 0x6d, 0x7e, 0x6f, 0x2f, 0xcf,
	0xbe, 0x67, 0x51, 0x5d, 0x85, 0x3b, 0x1e, 0xbc, 0x63, 0x9f, 0xff, 0xee, 0x41, 0xdf, 0x4c, 0x38,
	0xba, 0x5a, 0x2b, 0x47, 0x77, 0xb0, 0x6f, 0x7c, 0xbc, 0x0d, 0x5a, 0x36, 0x44, 0x27, 0x3f, 0xbf,
	0xfe, 0xfb, 0x97, 0xce, 0xdb, 0xd1, 0x5b, 0x33, 0x3d, 0x63, 0xee, 0xef, 0xc1, 0x85, 0xf7, 0x18,
	0x65, 0x30, 0x72, 0x3f, 0x87, 0x68, 0x7c, 0xff, 0xa7, 0x7a, 0xfc, 0xce, 0x9d, 0xbe, 0xe6, 0x98,
	0x77, 0xcd, 0x31, 0xa7, 0x51, 0xe0, 0x1e, 0x43, 0x9c, 0xc8, 0x0b, 0xef, 0xf1, 0xf5, 0x9e, 0xf9,
	0x79, 0xf8, 0xf8, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x2a, 0xdf, 0xf7, 0xb4, 0x08, 0x00,
	0x00,
}
