// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: examples/proto/hello/api.proto

package hello

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

type TestApiService interface {
	Version(ctx context.Context, in *TestReq) (*TestApiOutput, error)

	VersionServer(context.Context, *TestReq) (*TestApiOutput, error)

	VersionTest(ctx context.Context, in *TestReq) (*TestApiOutput, error)

	VersionTestServer(context.Context, *TestReq) (*TestApiOutput, error)
}

type TestApiV2Service interface {
	Version(ctx context.Context, in *TestReq) (*TestApiOutput, error)

	VersionServer(context.Context, *TestReq) (*TestApiOutput, error)

	VersionTest(ctx context.Context, in *TestReq) (*TestApiOutput, error)

	VersionTestServer(context.Context, *TestReq) (*TestApiOutput, error)
}
