// Code generated by protoc-gen-golug. DO NOT EDIT.
// source: examples/proto/hello/api.proto

package hello

import (
	"reflect"

	"github.com/pubgo/golug/client/grpclient"
	"github.com/pubgo/golug/xgen"
	"google.golang.org/grpc"
)

func GetTestApiClient(srv string, opts ...grpc.DialOption) func() (TestApiClient, error) {
	client := grpclient.Client(srv, opts...)
	return func() (TestApiClient, error) {
		c, err := client.Get()
		return &testApiClient{c}, err
	}
}

func GetTestApiV2Client(srv string, opts ...grpc.DialOption) func() (TestApiV2Client, error) {
	client := grpclient.Client(srv, opts...)
	return func() (TestApiV2Client, error) {
		c, err := client.Get()
		return &testApiV2Client{c}, err
	}
}

func init() {

	var mthList []xgen.GrpcRestHandler
	xgen.Add(reflect.ValueOf(RegisterServer), mthList)

	xgen.Add(reflect.ValueOf(RegisterHandlerFromEndpoint), nil)

	var mthList []xgen.GrpcRestHandler
	xgen.Add(reflect.ValueOf(RegisterServer), mthList)

	xgen.Add(reflect.ValueOf(RegisterHandlerFromEndpoint), nil)

}
