// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: examples/proto/hello/transport.proto

package hello

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context

type TransportService interface {
	TestStream(ctx context.Context) (Transport_TestStreamService, error)

	TestStreamServer(context.ContextTransport_TestStreamStream) error

	TestStream1(ctx context.Context) (Transport_TestStream1Service, error)

	TestStream1Server(context.ContextTransport_TestStream1Stream) error

	TestStream2(ctx context.Context, in *Message) (Transport_TestStream2Service, error)

	TestStream2Server(context.Context, *MessageTransport_TestStream2Stream) error

	TestStream3(ctx context.Context, in *Message) (*Message, error)

	TestStream3Server(context.Context, *Message) (*Message, error)
}
