// Code generated by protoc-gen-golug. DO NOT EDIT.
// source: examples/proto/hello/transport.proto

package hello

import (
	"reflect"

	"github.com/pubgo/golug/client/grpclient"
	"github.com/pubgo/golug/xgen"
	"google.golang.org/grpc"
)

func GetTransportClient(srv string, opts ...grpc.DialOption) func() (TransportClient, error) {
	client := grpclient.Client(srv, opts...)
	return func() (TransportClient, error) {
		c, err := client.Get()
		return &transportClient{c}, err
	}
}

func init() {

	var mthList []xgen.GrpcRestHandler
	xgen.Add(reflect.ValueOf(RegisterServer), mthList)

}
