// Code generated by qtc from "micro.tpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line examples/protoc-gen-micro/micro.tpl:1
package main

//line examples/protoc-gen-micro/micro.tpl:3
import gen "github.com/pubgo/xprotogen/gen"

//line examples/protoc-gen-micro/micro.tpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line examples/protoc-gen-micro/micro.tpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line examples/protoc-gen-micro/micro.tpl:5
func StreamHeader(qw422016 *qt422016.Writer, pkg string, fd *gen.FileDescriptor) {
//line examples/protoc-gen-micro/micro.tpl:5
	qw422016.N().S(`
    // Code generated by protoc-gen-micro. DO NOT EDIT.
`)
//line examples/protoc-gen-micro/micro.tpl:7
	if fd.GetOptions().GetDeprecated() {
//line examples/protoc-gen-micro/micro.tpl:7
		qw422016.N().S(`        // `)
//line examples/protoc-gen-micro/micro.tpl:8
		qw422016.E().S(fd.GetName())
//line examples/protoc-gen-micro/micro.tpl:8
		qw422016.N().S(` is a deprecated file.
`)
//line examples/protoc-gen-micro/micro.tpl:9
	} else {
//line examples/protoc-gen-micro/micro.tpl:9
		qw422016.N().S(`        // source: `)
//line examples/protoc-gen-micro/micro.tpl:10
		qw422016.E().S(fd.GetName())
//line examples/protoc-gen-micro/micro.tpl:10
		qw422016.N().S(`
`)
//line examples/protoc-gen-micro/micro.tpl:11
	}
//line examples/protoc-gen-micro/micro.tpl:11
	qw422016.N().S(`
    package `)
//line examples/protoc-gen-micro/micro.tpl:13
	qw422016.E().S(pkg)
//line examples/protoc-gen-micro/micro.tpl:13
	qw422016.N().S(`

    import (
    	fmt "fmt"
    	math "math"
    	context "context"

        client "github.com/asim/go-micro/v3/client"
    	server "github.com/asim/go-micro/v3/server"
    	_ "github.com/gogo/protobuf/gogoproto"
    	proto "github.com/golang/protobuf/proto"
    	_ "google.golang.org/genproto/googleapis/api/annotations"
    )

    // Reference imports to suppress errors if they are not otherwise used.
    var _ = proto.Marshal
    var _ = fmt.Errorf
    var _ = math.Inf

    // This is a compile-time assertion to ensure that this generated file
    // is compatible with the proto package it is being compiled against.
    // A compilation error at this line likely means your copy of the
    // proto package needs to be updated.
    const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

    // Reference imports to suppress errors if they are not otherwise used.
    var _ context.Context
    var _ client.Option
    var _ server.Option
`)
//line examples/protoc-gen-micro/micro.tpl:42
}

//line examples/protoc-gen-micro/micro.tpl:42
func WriteHeader(qq422016 qtio422016.Writer, pkg string, fd *gen.FileDescriptor) {
//line examples/protoc-gen-micro/micro.tpl:42
	qw422016 := qt422016.AcquireWriter(qq422016)
//line examples/protoc-gen-micro/micro.tpl:42
	StreamHeader(qw422016, pkg, fd)
//line examples/protoc-gen-micro/micro.tpl:42
	qt422016.ReleaseWriter(qw422016)
//line examples/protoc-gen-micro/micro.tpl:42
}

//line examples/protoc-gen-micro/micro.tpl:42
func Header(pkg string, fd *gen.FileDescriptor) string {
//line examples/protoc-gen-micro/micro.tpl:42
	qb422016 := qt422016.AcquireByteBuffer()
//line examples/protoc-gen-micro/micro.tpl:42
	WriteHeader(qb422016, pkg, fd)
//line examples/protoc-gen-micro/micro.tpl:42
	qs422016 := string(qb422016.B)
//line examples/protoc-gen-micro/micro.tpl:42
	qt422016.ReleaseByteBuffer(qb422016)
//line examples/protoc-gen-micro/micro.tpl:42
	return qs422016
//line examples/protoc-gen-micro/micro.tpl:42
}

//line examples/protoc-gen-micro/micro.tpl:45
func StreamService(qw422016 *qt422016.Writer, ss *gen.Service) {
//line examples/protoc-gen-micro/micro.tpl:45
	qw422016.N().S(`
    `)
//line examples/protoc-gen-micro/micro.tpl:47
	service := ss.GetName()
	service1 := gen.UnExport(ss.GetName())

//line examples/protoc-gen-micro/micro.tpl:49
	qw422016.N().S(`

    // Client API for @service service
    type `)
//line examples/protoc-gen-micro/micro.tpl:52
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:52
	qw422016.N().S(`Service interface {
`)
//line examples/protoc-gen-micro/micro.tpl:53
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:53
		qw422016.N().S(`            `)
//line examples/protoc-gen-micro/micro.tpl:54
		qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:54
		qw422016.N().S(`(ctx context.Context, in *`)
//line examples/protoc-gen-micro/micro.tpl:54
		qw422016.E().S(m.GetInputType())
//line examples/protoc-gen-micro/micro.tpl:54
		qw422016.N().S(`, opts ...client.CallOption) (* `)
//line examples/protoc-gen-micro/micro.tpl:54
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:54
		qw422016.N().S(`, error)
`)
//line examples/protoc-gen-micro/micro.tpl:55
	}
//line examples/protoc-gen-micro/micro.tpl:55
	qw422016.N().S(`    }

    type `)
//line examples/protoc-gen-micro/micro.tpl:58
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:58
	qw422016.N().S(`Service struct {
        c    client.Client
        name string
    }

    func New`)
//line examples/protoc-gen-micro/micro.tpl:63
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:63
	qw422016.N().S(`Service(name string, c client.Client) `)
//line examples/protoc-gen-micro/micro.tpl:63
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:63
	qw422016.N().S(`Service {
        return &`)
//line examples/protoc-gen-micro/micro.tpl:64
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:64
	qw422016.N().S(`Service{
            c:    c,
            name: name,
        }
    }

    `)
//line examples/protoc-gen-micro/micro.tpl:70
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:70
		qw422016.N().S(`
        func (c * `)
//line examples/protoc-gen-micro/micro.tpl:71
		qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:71
		qw422016.N().S(`Service) `)
//line examples/protoc-gen-micro/micro.tpl:71
		qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:71
		qw422016.N().S(`(ctx context.Context, in *`)
//line examples/protoc-gen-micro/micro.tpl:71
		qw422016.E().S(m.GetInputType())
//line examples/protoc-gen-micro/micro.tpl:71
		qw422016.N().S(`, opts ...client.CallOption) (* `)
//line examples/protoc-gen-micro/micro.tpl:71
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:71
		qw422016.N().S(`, error) {
            req := c.c.NewRequest(c.name, "`)
//line examples/protoc-gen-micro/micro.tpl:72
		qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:72
		qw422016.N().S(`.`)
//line examples/protoc-gen-micro/micro.tpl:72
		qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:72
		qw422016.N().S(`", in)
            out := new(`)
//line examples/protoc-gen-micro/micro.tpl:73
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:73
		qw422016.N().S(`)
            err := c.c.Call(ctx, req, out, opts...)
            if err != nil {
                return nil, err
            }
            return out, nil
        }
    `)
//line examples/protoc-gen-micro/micro.tpl:80
	}
//line examples/protoc-gen-micro/micro.tpl:80
	qw422016.N().S(`

    // Server API for `)
//line examples/protoc-gen-micro/micro.tpl:82
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:82
	qw422016.N().S(` service
    type `)
//line examples/protoc-gen-micro/micro.tpl:83
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:83
	qw422016.N().S(`Handler interface {
`)
//line examples/protoc-gen-micro/micro.tpl:84
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:84
		qw422016.N().S(`            `)
//line examples/protoc-gen-micro/micro.tpl:85
		qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:85
		qw422016.N().S(`(context.Context, *`)
//line examples/protoc-gen-micro/micro.tpl:85
		qw422016.E().S(m.GetInputType())
//line examples/protoc-gen-micro/micro.tpl:85
		qw422016.N().S(`, *`)
//line examples/protoc-gen-micro/micro.tpl:85
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:85
		qw422016.N().S(`) error
`)
//line examples/protoc-gen-micro/micro.tpl:86
	}
//line examples/protoc-gen-micro/micro.tpl:86
	qw422016.N().S(`    }

    func Register`)
//line examples/protoc-gen-micro/micro.tpl:89
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:89
	qw422016.N().S(`Handler(s server.Server, hdlr `)
//line examples/protoc-gen-micro/micro.tpl:89
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:89
	qw422016.N().S(`Handler, opts ...server.HandlerOption) error {
        type `)
//line examples/protoc-gen-micro/micro.tpl:90
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:90
	qw422016.N().S(` interface {
`)
//line examples/protoc-gen-micro/micro.tpl:91
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:91
		qw422016.N().S(`                `)
//line examples/protoc-gen-micro/micro.tpl:92
		qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:92
		qw422016.N().S(`(ctx context.Context,in *`)
//line examples/protoc-gen-micro/micro.tpl:92
		qw422016.E().S(m.GetInputType())
//line examples/protoc-gen-micro/micro.tpl:92
		qw422016.N().S(`,out *`)
//line examples/protoc-gen-micro/micro.tpl:92
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:92
		qw422016.N().S(`) error
`)
//line examples/protoc-gen-micro/micro.tpl:93
	}
//line examples/protoc-gen-micro/micro.tpl:93
	qw422016.N().S(`        }
        type `)
//line examples/protoc-gen-micro/micro.tpl:95
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:95
	qw422016.N().S(` struct {
            `)
//line examples/protoc-gen-micro/micro.tpl:96
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:96
	qw422016.N().S(`
        }
        h := &`)
//line examples/protoc-gen-micro/micro.tpl:98
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:98
	qw422016.N().S(`Handler{hdlr}
        return s.Handle(s.NewHandler(&`)
//line examples/protoc-gen-micro/micro.tpl:99
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:99
	qw422016.N().S(`{h}, opts...))
    }

    type `)
//line examples/protoc-gen-micro/micro.tpl:102
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:102
	qw422016.N().S(`Handler struct {
        `)
//line examples/protoc-gen-micro/micro.tpl:103
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:103
	qw422016.N().S(`Handler
    }

    `)
//line examples/protoc-gen-micro/micro.tpl:106
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:106
		qw422016.N().S(`
        func (h *`)
//line examples/protoc-gen-micro/micro.tpl:107
		qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:107
		qw422016.N().S(`Handler) `)
//line examples/protoc-gen-micro/micro.tpl:107
		qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:107
		qw422016.N().S(`(ctx context.Context, in *`)
//line examples/protoc-gen-micro/micro.tpl:107
		qw422016.E().S(m.GetInputType())
//line examples/protoc-gen-micro/micro.tpl:107
		qw422016.N().S(`, out *`)
//line examples/protoc-gen-micro/micro.tpl:107
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:107
		qw422016.N().S(`) error {
            return h.`)
//line examples/protoc-gen-micro/micro.tpl:108
		qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:108
		qw422016.N().S(`Handler.Version(ctx, in, out)
        }
    `)
//line examples/protoc-gen-micro/micro.tpl:110
	}
//line examples/protoc-gen-micro/micro.tpl:110
	qw422016.N().S(`


    `)
//line examples/protoc-gen-micro/micro.tpl:113
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:113
		qw422016.N().S(`
        `)
//line examples/protoc-gen-micro/micro.tpl:115
		method, path := m.GetHttpMethod()

//line examples/protoc-gen-micro/micro.tpl:116
		qw422016.N().S(`
        // `)
//line examples/protoc-gen-micro/micro.tpl:117
		qw422016.E().S(method)
//line examples/protoc-gen-micro/micro.tpl:117
		qw422016.N().S(`
        // `)
//line examples/protoc-gen-micro/micro.tpl:118
		qw422016.E().S(path)
//line examples/protoc-gen-micro/micro.tpl:118
		qw422016.N().S(`
    `)
//line examples/protoc-gen-micro/micro.tpl:119
	}
//line examples/protoc-gen-micro/micro.tpl:119
	qw422016.N().S(`
`)
//line examples/protoc-gen-micro/micro.tpl:120
}

//line examples/protoc-gen-micro/micro.tpl:120
func WriteService(qq422016 qtio422016.Writer, ss *gen.Service) {
//line examples/protoc-gen-micro/micro.tpl:120
	qw422016 := qt422016.AcquireWriter(qq422016)
//line examples/protoc-gen-micro/micro.tpl:120
	StreamService(qw422016, ss)
//line examples/protoc-gen-micro/micro.tpl:120
	qt422016.ReleaseWriter(qw422016)
//line examples/protoc-gen-micro/micro.tpl:120
}

//line examples/protoc-gen-micro/micro.tpl:120
func Service(ss *gen.Service) string {
//line examples/protoc-gen-micro/micro.tpl:120
	qb422016 := qt422016.AcquireByteBuffer()
//line examples/protoc-gen-micro/micro.tpl:120
	WriteService(qb422016, ss)
//line examples/protoc-gen-micro/micro.tpl:120
	qs422016 := string(qb422016.B)
//line examples/protoc-gen-micro/micro.tpl:120
	qt422016.ReleaseByteBuffer(qb422016)
//line examples/protoc-gen-micro/micro.tpl:120
	return qs422016
//line examples/protoc-gen-micro/micro.tpl:120
}
