// Code generated by qtc from "micro.tpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line examples/protoc-gen-micro/micro.tpl:1
package main

//line examples/protoc-gen-micro/micro.tpl:3
import gen "github.com/pubgo/xprotogen/gen"

//line examples/protoc-gen-micro/micro.tpl:4
import "strings"

//line examples/protoc-gen-micro/micro.tpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line examples/protoc-gen-micro/micro.tpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line examples/protoc-gen-micro/micro.tpl:6
func StreamHeader(qw422016 *qt422016.Writer, pkg string, fd *gen.FileDescriptor) {
//line examples/protoc-gen-micro/micro.tpl:6
	qw422016.N().S(`
    // Code generated by protoc-gen-micro. DO NOT EDIT.
`)
//line examples/protoc-gen-micro/micro.tpl:8
	if fd.GetOptions().GetDeprecated() {
//line examples/protoc-gen-micro/micro.tpl:8
		qw422016.N().S(`        // `)
//line examples/protoc-gen-micro/micro.tpl:9
		qw422016.E().S(fd.GetName())
//line examples/protoc-gen-micro/micro.tpl:9
		qw422016.N().S(` is a deprecated file.
`)
//line examples/protoc-gen-micro/micro.tpl:10
	} else {
//line examples/protoc-gen-micro/micro.tpl:10
		qw422016.N().S(`        // source: `)
//line examples/protoc-gen-micro/micro.tpl:11
		qw422016.E().S(fd.GetName())
//line examples/protoc-gen-micro/micro.tpl:11
		qw422016.N().S(`
`)
//line examples/protoc-gen-micro/micro.tpl:12
	}
//line examples/protoc-gen-micro/micro.tpl:12
	qw422016.N().S(`
    package `)
//line examples/protoc-gen-micro/micro.tpl:14
	qw422016.E().S(pkg)
//line examples/protoc-gen-micro/micro.tpl:14
	qw422016.N().S(`

    import (
    	fmt "fmt"
    	math "math"
    	context "context"

        client "github.com/asim/go-micro/v3/client"
    	server "github.com/asim/go-micro/v3/server"
    	_ "github.com/gogo/protobuf/gogoproto"
    	proto "github.com/golang/protobuf/proto"
    	_ "google.golang.org/genproto/googleapis/api/annotations"
    )

    // Reference imports to suppress errors if they are not otherwise used.
    var _ = proto.Marshal
    var _ = fmt.Errorf
    var _ = math.Inf

    // This is a compile-time assertion to ensure that this generated file
    // is compatible with the proto package it is being compiled against.
    // A compilation error at this line likely means your copy of the
    // proto package needs to be updated.
    const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

    // Reference imports to suppress errors if they are not otherwise used.
    var _ context.Context
    var _ client.Option
    var _ server.Option
`)
//line examples/protoc-gen-micro/micro.tpl:43
}

//line examples/protoc-gen-micro/micro.tpl:43
func WriteHeader(qq422016 qtio422016.Writer, pkg string, fd *gen.FileDescriptor) {
//line examples/protoc-gen-micro/micro.tpl:43
	qw422016 := qt422016.AcquireWriter(qq422016)
//line examples/protoc-gen-micro/micro.tpl:43
	StreamHeader(qw422016, pkg, fd)
//line examples/protoc-gen-micro/micro.tpl:43
	qt422016.ReleaseWriter(qw422016)
//line examples/protoc-gen-micro/micro.tpl:43
}

//line examples/protoc-gen-micro/micro.tpl:43
func Header(pkg string, fd *gen.FileDescriptor) string {
//line examples/protoc-gen-micro/micro.tpl:43
	qb422016 := qt422016.AcquireByteBuffer()
//line examples/protoc-gen-micro/micro.tpl:43
	WriteHeader(qb422016, pkg, fd)
//line examples/protoc-gen-micro/micro.tpl:43
	qs422016 := string(qb422016.B)
//line examples/protoc-gen-micro/micro.tpl:43
	qt422016.ReleaseByteBuffer(qb422016)
//line examples/protoc-gen-micro/micro.tpl:43
	return qs422016
//line examples/protoc-gen-micro/micro.tpl:43
}

//line examples/protoc-gen-micro/micro.tpl:45
func streamserviceClient(qw422016 *qt422016.Writer, srv string, m *gen.Method) {
//line examples/protoc-gen-micro/micro.tpl:45
	qw422016.N().S(`
    func (c *`)
//line examples/protoc-gen-micro/micro.tpl:46
	qw422016.E().S(gen.UnExport(srv))
//line examples/protoc-gen-micro/micro.tpl:46
	qw422016.N().S(`Service)`)
//line examples/protoc-gen-micro/micro.tpl:46
	qw422016.E().S(clientMethod(srv, m))
//line examples/protoc-gen-micro/micro.tpl:46
	qw422016.N().S(`{
        `)
//line examples/protoc-gen-micro/micro.tpl:47
	if !m.GetServerStreaming() && !m.GetClientStreaming() {
//line examples/protoc-gen-micro/micro.tpl:47
		qw422016.N().S(`
            req := c.c.NewRequest(c.name, "`)
//line examples/protoc-gen-micro/micro.tpl:48
		qw422016.E().S(srv)
//line examples/protoc-gen-micro/micro.tpl:48
		qw422016.N().S(`.`)
//line examples/protoc-gen-micro/micro.tpl:48
		qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:48
		qw422016.N().S(`", in)
            out := new(`)
//line examples/protoc-gen-micro/micro.tpl:49
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:49
		qw422016.N().S(`)
            err := c.c.Call(ctx, req, out, opts...)
            if err != nil {
                return nil, err
            }
            return out, nil
        `)
//line examples/protoc-gen-micro/micro.tpl:55
	} else {
//line examples/protoc-gen-micro/micro.tpl:55
		qw422016.N().S(`
            req := c.c.NewRequest(c.name, "`)
//line examples/protoc-gen-micro/micro.tpl:56
		qw422016.E().S(srv)
//line examples/protoc-gen-micro/micro.tpl:56
		qw422016.N().S(`.`)
//line examples/protoc-gen-micro/micro.tpl:56
		qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:56
		qw422016.N().S(`", &`)
//line examples/protoc-gen-micro/micro.tpl:56
		qw422016.E().S(m.GetInputType())
//line examples/protoc-gen-micro/micro.tpl:56
		qw422016.N().S(`{})
            stream, err := c.c.Stream(ctx, req, opts...)
            if err != nil { return nil, err }
            `)
//line examples/protoc-gen-micro/micro.tpl:59
		if !m.GetClientStreaming() {
//line examples/protoc-gen-micro/micro.tpl:59
			qw422016.N().S(`
                if err := stream.Send(in); err != nil { return nil, err }
            `)
//line examples/protoc-gen-micro/micro.tpl:61
		}
//line examples/protoc-gen-micro/micro.tpl:61
		qw422016.N().S(`

            return &`)
//line examples/protoc-gen-micro/micro.tpl:63
		qw422016.E().S(gen.UnExport(srv) + m.GetName())
//line examples/protoc-gen-micro/micro.tpl:63
		qw422016.N().S(`{stream}, nil
        `)
//line examples/protoc-gen-micro/micro.tpl:64
	}
//line examples/protoc-gen-micro/micro.tpl:64
	qw422016.N().S(`
    }


    // Stream auxiliary types and methods.
    type `)
//line examples/protoc-gen-micro/micro.tpl:69
	qw422016.E().S(srv)
//line examples/protoc-gen-micro/micro.tpl:69
	qw422016.N().S(`_`)
//line examples/protoc-gen-micro/micro.tpl:69
	qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:69
	qw422016.N().S(`Service interface {
        Context() context.Context
        SendMsg(interface{}) error
        RecvMsg(interface{}) error
        Close() error
        `)
//line examples/protoc-gen-micro/micro.tpl:74
	if m.GetClientStreaming() {
//line examples/protoc-gen-micro/micro.tpl:74
		qw422016.N().S(`
            Send(*`)
//line examples/protoc-gen-micro/micro.tpl:75
		qw422016.E().S(m.GetInputType())
//line examples/protoc-gen-micro/micro.tpl:75
		qw422016.N().S(`) error
        `)
//line examples/protoc-gen-micro/micro.tpl:76
	}
//line examples/protoc-gen-micro/micro.tpl:76
	qw422016.N().S(`

        `)
//line examples/protoc-gen-micro/micro.tpl:78
	if m.GetServerStreaming() {
//line examples/protoc-gen-micro/micro.tpl:78
		qw422016.N().S(`
            Recv(*`)
//line examples/protoc-gen-micro/micro.tpl:79
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:79
		qw422016.N().S(`) error
        `)
//line examples/protoc-gen-micro/micro.tpl:80
	}
//line examples/protoc-gen-micro/micro.tpl:80
	qw422016.N().S(`
    }

    type `)
//line examples/protoc-gen-micro/micro.tpl:83
	qw422016.E().S(srv + m.GetName())
//line examples/protoc-gen-micro/micro.tpl:83
	qw422016.N().S(` struct {
        stream client.Stream
    }


    func (x *`)
//line examples/protoc-gen-micro/micro.tpl:88
	qw422016.E().S(srv + m.GetName())
//line examples/protoc-gen-micro/micro.tpl:88
	qw422016.N().S(`) Close() error {
    	return x.stream.Close()
    }

    func (x *`)
//line examples/protoc-gen-micro/micro.tpl:92
	qw422016.E().S(srv + m.GetName())
//line examples/protoc-gen-micro/micro.tpl:92
	qw422016.N().S(`) Context() context.Context {
    	return x.stream.Context()
    }

    func (x *`)
//line examples/protoc-gen-micro/micro.tpl:96
	qw422016.E().S(srv + m.GetName())
//line examples/protoc-gen-micro/micro.tpl:96
	qw422016.N().S(`) SendMsg(m interface{}) error {
    	return x.stream.Send(m)
    }

    func (x *`)
//line examples/protoc-gen-micro/micro.tpl:100
	qw422016.E().S(srv + m.GetName())
//line examples/protoc-gen-micro/micro.tpl:100
	qw422016.N().S(`) RecvMsg(m interface{}) error {
    	return x.stream.Recv(m)
    }

    func (x *`)
//line examples/protoc-gen-micro/micro.tpl:104
	qw422016.E().S(srv + m.GetName())
//line examples/protoc-gen-micro/micro.tpl:104
	qw422016.N().S(`) Send(m *Message) error {
    	return x.stream.Send(m)
    }


    `)
//line examples/protoc-gen-micro/micro.tpl:109
	if m.GetClientStreaming() {
//line examples/protoc-gen-micro/micro.tpl:109
		qw422016.N().S(`
        func (x *`)
//line examples/protoc-gen-micro/micro.tpl:110
		qw422016.E().S(srv + m.GetName())
//line examples/protoc-gen-micro/micro.tpl:110
		qw422016.N().S(`) Send(m *`)
//line examples/protoc-gen-micro/micro.tpl:110
		qw422016.E().S(m.GetInputType())
//line examples/protoc-gen-micro/micro.tpl:110
		qw422016.N().S(`) error{
            return x.stream.Send(m)
        }
    `)
//line examples/protoc-gen-micro/micro.tpl:113
	}
//line examples/protoc-gen-micro/micro.tpl:113
	qw422016.N().S(`

    `)
//line examples/protoc-gen-micro/micro.tpl:115
	if m.GetServerStreaming() {
//line examples/protoc-gen-micro/micro.tpl:115
		qw422016.N().S(`
        func (x *`)
//line examples/protoc-gen-micro/micro.tpl:116
		qw422016.E().S(srv + m.GetName())
//line examples/protoc-gen-micro/micro.tpl:116
		qw422016.N().S(`) Recv() (*`)
//line examples/protoc-gen-micro/micro.tpl:116
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:116
		qw422016.N().S(`, error) {
            m := new(`)
//line examples/protoc-gen-micro/micro.tpl:117
		qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:117
		qw422016.N().S(`)
            err := x.stream.Recv(m)
            if err != nil {
                return nil, err
            }
                return m, nil
        }
    `)
//line examples/protoc-gen-micro/micro.tpl:124
	}
//line examples/protoc-gen-micro/micro.tpl:124
	qw422016.N().S(`


`)
//line examples/protoc-gen-micro/micro.tpl:127
}

//line examples/protoc-gen-micro/micro.tpl:127
func writeserviceClient(qq422016 qtio422016.Writer, srv string, m *gen.Method) {
//line examples/protoc-gen-micro/micro.tpl:127
	qw422016 := qt422016.AcquireWriter(qq422016)
//line examples/protoc-gen-micro/micro.tpl:127
	streamserviceClient(qw422016, srv, m)
//line examples/protoc-gen-micro/micro.tpl:127
	qt422016.ReleaseWriter(qw422016)
//line examples/protoc-gen-micro/micro.tpl:127
}

//line examples/protoc-gen-micro/micro.tpl:127
func serviceClient(srv string, m *gen.Method) string {
//line examples/protoc-gen-micro/micro.tpl:127
	qb422016 := qt422016.AcquireByteBuffer()
//line examples/protoc-gen-micro/micro.tpl:127
	writeserviceClient(qb422016, srv, m)
//line examples/protoc-gen-micro/micro.tpl:127
	qs422016 := string(qb422016.B)
//line examples/protoc-gen-micro/micro.tpl:127
	qt422016.ReleaseByteBuffer(qb422016)
//line examples/protoc-gen-micro/micro.tpl:127
	return qs422016
//line examples/protoc-gen-micro/micro.tpl:127
}

//line examples/protoc-gen-micro/micro.tpl:130
func streamclientMethod(qw422016 *qt422016.Writer, srv string, m *gen.Method) {
//line examples/protoc-gen-micro/micro.tpl:132
	reqArg := ", in *" + m.GetInputType()
	if m.GetClientStreaming() {
		reqArg = ""
	}

	respName := "*" + m.GetOutputType()
	if m.GetServerStreaming() || m.GetClientStreaming() {
		respName = srv + "_" + m.GetName() + "Service"
	}

//line examples/protoc-gen-micro/micro.tpl:142
	qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:142
	qw422016.N().S(`(ctx context.Context`)
//line examples/protoc-gen-micro/micro.tpl:142
	qw422016.E().S(reqArg)
//line examples/protoc-gen-micro/micro.tpl:142
	qw422016.N().S(`, opts ...client.CallOption) (`)
//line examples/protoc-gen-micro/micro.tpl:142
	qw422016.E().S(respName)
//line examples/protoc-gen-micro/micro.tpl:142
	qw422016.N().S(`, error)`)
//line examples/protoc-gen-micro/micro.tpl:143
}

//line examples/protoc-gen-micro/micro.tpl:143
func writeclientMethod(qq422016 qtio422016.Writer, srv string, m *gen.Method) {
//line examples/protoc-gen-micro/micro.tpl:143
	qw422016 := qt422016.AcquireWriter(qq422016)
//line examples/protoc-gen-micro/micro.tpl:143
	streamclientMethod(qw422016, srv, m)
//line examples/protoc-gen-micro/micro.tpl:143
	qt422016.ReleaseWriter(qw422016)
//line examples/protoc-gen-micro/micro.tpl:143
}

//line examples/protoc-gen-micro/micro.tpl:143
func clientMethod(srv string, m *gen.Method) string {
//line examples/protoc-gen-micro/micro.tpl:143
	qb422016 := qt422016.AcquireByteBuffer()
//line examples/protoc-gen-micro/micro.tpl:143
	writeclientMethod(qb422016, srv, m)
//line examples/protoc-gen-micro/micro.tpl:143
	qs422016 := string(qb422016.B)
//line examples/protoc-gen-micro/micro.tpl:143
	qt422016.ReleaseByteBuffer(qb422016)
//line examples/protoc-gen-micro/micro.tpl:143
	return qs422016
//line examples/protoc-gen-micro/micro.tpl:143
}

//line examples/protoc-gen-micro/micro.tpl:148
func streamserverMethod(qw422016 *qt422016.Writer, srv string, m *gen.Method) {
//line examples/protoc-gen-micro/micro.tpl:150
	var reqArgs []string
	if !m.GetClientStreaming() {
		reqArgs = append(reqArgs, "*"+m.GetInputType())
	}
	if m.GetServerStreaming() || m.GetClientStreaming() {
		reqArgs = append(reqArgs, srv+"_"+m.GetName()+"Stream")
	}
	if !m.GetClientStreaming() && !m.GetServerStreaming() {
		reqArgs = append(reqArgs, "*"+m.GetOutputType())
	}

//line examples/protoc-gen-micro/micro.tpl:161
	qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:161
	qw422016.N().S(`(context.Context,`)
//line examples/protoc-gen-micro/micro.tpl:161
	qw422016.E().S(strings.Join(reqArgs, ", "))
//line examples/protoc-gen-micro/micro.tpl:161
	qw422016.N().S(`) error`)
//line examples/protoc-gen-micro/micro.tpl:162
}

//line examples/protoc-gen-micro/micro.tpl:162
func writeserverMethod(qq422016 qtio422016.Writer, srv string, m *gen.Method) {
//line examples/protoc-gen-micro/micro.tpl:162
	qw422016 := qt422016.AcquireWriter(qq422016)
//line examples/protoc-gen-micro/micro.tpl:162
	streamserverMethod(qw422016, srv, m)
//line examples/protoc-gen-micro/micro.tpl:162
	qt422016.ReleaseWriter(qw422016)
//line examples/protoc-gen-micro/micro.tpl:162
}

//line examples/protoc-gen-micro/micro.tpl:162
func serverMethod(srv string, m *gen.Method) string {
//line examples/protoc-gen-micro/micro.tpl:162
	qb422016 := qt422016.AcquireByteBuffer()
//line examples/protoc-gen-micro/micro.tpl:162
	writeserverMethod(qb422016, srv, m)
//line examples/protoc-gen-micro/micro.tpl:162
	qs422016 := string(qb422016.B)
//line examples/protoc-gen-micro/micro.tpl:162
	qt422016.ReleaseByteBuffer(qb422016)
//line examples/protoc-gen-micro/micro.tpl:162
	return qs422016
//line examples/protoc-gen-micro/micro.tpl:162
}

//line examples/protoc-gen-micro/micro.tpl:166
func streamserviceServer(qw422016 *qt422016.Writer, srv string, m *gen.Method) {
//line examples/protoc-gen-micro/micro.tpl:168
	methName := m.GetName()
	serveType := srv + "Handler"
	inType := m.GetInputType()
	outType := m.GetOutputType()
	unexport := gen.UnExport
	streamType := unexport(srv) + methName + "Stream"

//line examples/protoc-gen-micro/micro.tpl:174
	qw422016.N().S(`
    `)
//line examples/protoc-gen-micro/micro.tpl:176
	if !m.GetServerStreaming() && !m.GetClientStreaming() {
//line examples/protoc-gen-micro/micro.tpl:176
		qw422016.N().S(`
        func (h *`)
//line examples/protoc-gen-micro/micro.tpl:177
		qw422016.E().S(unexport(srv))
//line examples/protoc-gen-micro/micro.tpl:177
		qw422016.N().S(`Handler)`)
//line examples/protoc-gen-micro/micro.tpl:177
		qw422016.E().S(methName)
//line examples/protoc-gen-micro/micro.tpl:177
		qw422016.N().S(`(ctx context.Context, in *`)
//line examples/protoc-gen-micro/micro.tpl:177
		qw422016.E().S(inType)
//line examples/protoc-gen-micro/micro.tpl:177
		qw422016.N().S(`, out *`)
//line examples/protoc-gen-micro/micro.tpl:177
		qw422016.E().S(outType)
//line examples/protoc-gen-micro/micro.tpl:177
		qw422016.N().S(`) error {
    		return h.`)
//line examples/protoc-gen-micro/micro.tpl:178
		qw422016.E().S(serveType)
//line examples/protoc-gen-micro/micro.tpl:178
		qw422016.N().S(`.`)
//line examples/protoc-gen-micro/micro.tpl:178
		qw422016.E().S(methName)
//line examples/protoc-gen-micro/micro.tpl:178
		qw422016.N().S(`(ctx, in, out)
        }
        `)
//line examples/protoc-gen-micro/micro.tpl:180
		return
//line examples/protoc-gen-micro/micro.tpl:181
	}
//line examples/protoc-gen-micro/micro.tpl:181
	qw422016.N().S(`

    func (h *`)
//line examples/protoc-gen-micro/micro.tpl:183
	qw422016.E().S(unexport(srv))
//line examples/protoc-gen-micro/micro.tpl:183
	qw422016.N().S(`Handler)`)
//line examples/protoc-gen-micro/micro.tpl:183
	qw422016.E().S(methName)
//line examples/protoc-gen-micro/micro.tpl:183
	qw422016.N().S(`(ctx context.Context, stream server.Stream) error {
        `)
//line examples/protoc-gen-micro/micro.tpl:184
	if !m.GetClientStreaming() {
//line examples/protoc-gen-micro/micro.tpl:184
		qw422016.N().S(`
            m := new(`)
//line examples/protoc-gen-micro/micro.tpl:185
		qw422016.E().S(inType)
//line examples/protoc-gen-micro/micro.tpl:185
		qw422016.N().S(`)
            if err := stream.Recv(m); err != nil { return err }
            return h.`)
//line examples/protoc-gen-micro/micro.tpl:187
		qw422016.E().S(serveType)
//line examples/protoc-gen-micro/micro.tpl:187
		qw422016.N().S(`.`)
//line examples/protoc-gen-micro/micro.tpl:187
		qw422016.E().S(methName)
//line examples/protoc-gen-micro/micro.tpl:187
		qw422016.N().S(`(ctx, m, &`)
//line examples/protoc-gen-micro/micro.tpl:187
		qw422016.E().S(streamType)
//line examples/protoc-gen-micro/micro.tpl:187
		qw422016.N().S(`{stream})
        `)
//line examples/protoc-gen-micro/micro.tpl:188
	} else {
//line examples/protoc-gen-micro/micro.tpl:188
		qw422016.N().S(`
            return h.`)
//line examples/protoc-gen-micro/micro.tpl:189
		qw422016.E().S(serveType)
//line examples/protoc-gen-micro/micro.tpl:189
		qw422016.N().S(`.`)
//line examples/protoc-gen-micro/micro.tpl:189
		qw422016.E().S(methName)
//line examples/protoc-gen-micro/micro.tpl:189
		qw422016.N().S(`(ctx, &`)
//line examples/protoc-gen-micro/micro.tpl:189
		qw422016.E().S(streamType)
//line examples/protoc-gen-micro/micro.tpl:189
		qw422016.N().S(`{stream})
        `)
//line examples/protoc-gen-micro/micro.tpl:190
	}
//line examples/protoc-gen-micro/micro.tpl:190
	qw422016.N().S(`
    }


    type `)
//line examples/protoc-gen-micro/micro.tpl:194
	qw422016.E().S(srv + "_" + methName)
//line examples/protoc-gen-micro/micro.tpl:194
	qw422016.N().S(`Stream interface {
        Context() context.Context
        SendMsg(interface{}) error
        RecvMsg(interface{}) error
        Close() error
        `)
//line examples/protoc-gen-micro/micro.tpl:199
	if m.GetServerStreaming() {
//line examples/protoc-gen-micro/micro.tpl:199
		qw422016.N().S(`
            Send(*`)
//line examples/protoc-gen-micro/micro.tpl:200
		qw422016.E().S(outType)
//line examples/protoc-gen-micro/micro.tpl:200
		qw422016.N().S(`) error
        `)
//line examples/protoc-gen-micro/micro.tpl:201
	}
//line examples/protoc-gen-micro/micro.tpl:201
	qw422016.N().S(`

        `)
//line examples/protoc-gen-micro/micro.tpl:203
	if m.GetClientStreaming() {
//line examples/protoc-gen-micro/micro.tpl:203
		qw422016.N().S(`
            Recv() (*`)
//line examples/protoc-gen-micro/micro.tpl:204
		qw422016.E().S(inType)
//line examples/protoc-gen-micro/micro.tpl:204
		qw422016.N().S(`, error)
        `)
//line examples/protoc-gen-micro/micro.tpl:205
	}
//line examples/protoc-gen-micro/micro.tpl:205
	qw422016.N().S(`
    }

    type `)
//line examples/protoc-gen-micro/micro.tpl:208
	qw422016.E().S(streamType)
//line examples/protoc-gen-micro/micro.tpl:208
	qw422016.N().S(` struct {
        stream server.Stream
    }


    func (x *`)
//line examples/protoc-gen-micro/micro.tpl:213
	qw422016.E().S(streamType)
//line examples/protoc-gen-micro/micro.tpl:213
	qw422016.N().S(`) Close() error {
    	return x.stream.Close()
    }

    func (x *`)
//line examples/protoc-gen-micro/micro.tpl:217
	qw422016.E().S(streamType)
//line examples/protoc-gen-micro/micro.tpl:217
	qw422016.N().S(`) Context() context.Context {
    	return x.stream.Context()
    }

    func (x *`)
//line examples/protoc-gen-micro/micro.tpl:221
	qw422016.E().S(streamType)
//line examples/protoc-gen-micro/micro.tpl:221
	qw422016.N().S(`) SendMsg(m interface{}) error {
    	return x.stream.Send(m)
    }

    func (x *`)
//line examples/protoc-gen-micro/micro.tpl:225
	qw422016.E().S(streamType)
//line examples/protoc-gen-micro/micro.tpl:225
	qw422016.N().S(`) RecvMsg(m interface{}) error {
    	return x.stream.Recv(m)
    }

    `)
//line examples/protoc-gen-micro/micro.tpl:229
	if m.GetServerStreaming() {
//line examples/protoc-gen-micro/micro.tpl:229
		qw422016.N().S(`
        func (x *`)
//line examples/protoc-gen-micro/micro.tpl:230
		qw422016.E().S(streamType)
//line examples/protoc-gen-micro/micro.tpl:230
		qw422016.N().S(`) Send(*`)
//line examples/protoc-gen-micro/micro.tpl:230
		qw422016.E().S(outType)
//line examples/protoc-gen-micro/micro.tpl:230
		qw422016.N().S(`) error {
            return x.stream.Send(m)
        }
    `)
//line examples/protoc-gen-micro/micro.tpl:233
	}
//line examples/protoc-gen-micro/micro.tpl:233
	qw422016.N().S(`

    `)
//line examples/protoc-gen-micro/micro.tpl:235
	if m.GetClientStreaming() {
//line examples/protoc-gen-micro/micro.tpl:235
		qw422016.N().S(`
        func (x *`)
//line examples/protoc-gen-micro/micro.tpl:236
		qw422016.E().S(streamType)
//line examples/protoc-gen-micro/micro.tpl:236
		qw422016.N().S(`) Recv() (*`)
//line examples/protoc-gen-micro/micro.tpl:236
		qw422016.E().S(inType)
//line examples/protoc-gen-micro/micro.tpl:236
		qw422016.N().S(`, error) {
            m := new(`)
//line examples/protoc-gen-micro/micro.tpl:237
		qw422016.E().S(inType)
//line examples/protoc-gen-micro/micro.tpl:237
		qw422016.N().S(`)
            if err := x.stream.Recv(m); err != nil { return nil, err }
            return m, nil
        }
    `)
//line examples/protoc-gen-micro/micro.tpl:241
	}
//line examples/protoc-gen-micro/micro.tpl:241
	qw422016.N().S(`

`)
//line examples/protoc-gen-micro/micro.tpl:243
}

//line examples/protoc-gen-micro/micro.tpl:243
func writeserviceServer(qq422016 qtio422016.Writer, srv string, m *gen.Method) {
//line examples/protoc-gen-micro/micro.tpl:243
	qw422016 := qt422016.AcquireWriter(qq422016)
//line examples/protoc-gen-micro/micro.tpl:243
	streamserviceServer(qw422016, srv, m)
//line examples/protoc-gen-micro/micro.tpl:243
	qt422016.ReleaseWriter(qw422016)
//line examples/protoc-gen-micro/micro.tpl:243
}

//line examples/protoc-gen-micro/micro.tpl:243
func serviceServer(srv string, m *gen.Method) string {
//line examples/protoc-gen-micro/micro.tpl:243
	qb422016 := qt422016.AcquireByteBuffer()
//line examples/protoc-gen-micro/micro.tpl:243
	writeserviceServer(qb422016, srv, m)
//line examples/protoc-gen-micro/micro.tpl:243
	qs422016 := string(qb422016.B)
//line examples/protoc-gen-micro/micro.tpl:243
	qt422016.ReleaseByteBuffer(qb422016)
//line examples/protoc-gen-micro/micro.tpl:243
	return qs422016
//line examples/protoc-gen-micro/micro.tpl:243
}

//line examples/protoc-gen-micro/micro.tpl:245
func StreamService(qw422016 *qt422016.Writer, ss *gen.Service) {
//line examples/protoc-gen-micro/micro.tpl:245
	qw422016.N().S(`
    `)
//line examples/protoc-gen-micro/micro.tpl:247
	service := ss.GetName()
	service1 := gen.UnExport(ss.GetName())

//line examples/protoc-gen-micro/micro.tpl:249
	qw422016.N().S(`

    // Client API for @service service
    type `)
//line examples/protoc-gen-micro/micro.tpl:252
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:252
	qw422016.N().S(`Service interface {
`)
//line examples/protoc-gen-micro/micro.tpl:253
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:253
		qw422016.N().S(`            `)
//line examples/protoc-gen-micro/micro.tpl:254
		qw422016.E().S(clientMethod(service, m))
//line examples/protoc-gen-micro/micro.tpl:254
		qw422016.N().S(`
`)
//line examples/protoc-gen-micro/micro.tpl:255
	}
//line examples/protoc-gen-micro/micro.tpl:255
	qw422016.N().S(`    }

    type `)
//line examples/protoc-gen-micro/micro.tpl:258
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:258
	qw422016.N().S(`Service struct {
        c    client.Client
        name string
    }

    func New`)
//line examples/protoc-gen-micro/micro.tpl:263
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:263
	qw422016.N().S(`Service(name string, c client.Client) `)
//line examples/protoc-gen-micro/micro.tpl:263
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:263
	qw422016.N().S(`Service {
        return &`)
//line examples/protoc-gen-micro/micro.tpl:264
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:264
	qw422016.N().S(`Service{
            c:    c,
            name: name,
        }
    }

`)
//line examples/protoc-gen-micro/micro.tpl:270
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:270
		qw422016.N().S(`        `)
//line examples/protoc-gen-micro/micro.tpl:271
		streamserviceClient(qw422016, service, m)
//line examples/protoc-gen-micro/micro.tpl:271
		qw422016.N().S(`
`)
//line examples/protoc-gen-micro/micro.tpl:272
	}
//line examples/protoc-gen-micro/micro.tpl:272
	qw422016.N().S(`
    // Server API for `)
//line examples/protoc-gen-micro/micro.tpl:274
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:274
	qw422016.N().S(` service
    type `)
//line examples/protoc-gen-micro/micro.tpl:275
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:275
	qw422016.N().S(`Handler interface {
`)
//line examples/protoc-gen-micro/micro.tpl:276
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:276
		qw422016.N().S(`            `)
//line examples/protoc-gen-micro/micro.tpl:277
		streamserverMethod(qw422016, service, m)
//line examples/protoc-gen-micro/micro.tpl:277
		qw422016.N().S(`
`)
//line examples/protoc-gen-micro/micro.tpl:278
	}
//line examples/protoc-gen-micro/micro.tpl:278
	qw422016.N().S(`    }

    func Register`)
//line examples/protoc-gen-micro/micro.tpl:281
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:281
	qw422016.N().S(`Handler(s server.Server, hdlr `)
//line examples/protoc-gen-micro/micro.tpl:281
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:281
	qw422016.N().S(`Handler, opts ...server.HandlerOption) error {
        type `)
//line examples/protoc-gen-micro/micro.tpl:282
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:282
	qw422016.N().S(` interface {
`)
//line examples/protoc-gen-micro/micro.tpl:283
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:283
		qw422016.N().S(`                `)
//line examples/protoc-gen-micro/micro.tpl:284
		if !m.GetServerStreaming() && !m.GetClientStreaming() {
//line examples/protoc-gen-micro/micro.tpl:284
			qw422016.N().S(`
                    `)
//line examples/protoc-gen-micro/micro.tpl:285
			qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:285
			qw422016.N().S(`(ctx context.Context,in *`)
//line examples/protoc-gen-micro/micro.tpl:285
			qw422016.E().S(m.GetInputType())
//line examples/protoc-gen-micro/micro.tpl:285
			qw422016.N().S(`,out *`)
//line examples/protoc-gen-micro/micro.tpl:285
			qw422016.E().S(m.GetOutputType())
//line examples/protoc-gen-micro/micro.tpl:285
			qw422016.N().S(`) error
                    `)
//line examples/protoc-gen-micro/micro.tpl:286
			continue
//line examples/protoc-gen-micro/micro.tpl:287
		}
//line examples/protoc-gen-micro/micro.tpl:287
		qw422016.N().S(`
                `)
//line examples/protoc-gen-micro/micro.tpl:288
		qw422016.E().S(m.GetName())
//line examples/protoc-gen-micro/micro.tpl:288
		qw422016.N().S(`(ctx context.Context,stream server.Stream)error
`)
//line examples/protoc-gen-micro/micro.tpl:289
	}
//line examples/protoc-gen-micro/micro.tpl:289
	qw422016.N().S(`        }
        type `)
//line examples/protoc-gen-micro/micro.tpl:291
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:291
	qw422016.N().S(` struct {
            `)
//line examples/protoc-gen-micro/micro.tpl:292
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:292
	qw422016.N().S(`
        }
        h := &`)
//line examples/protoc-gen-micro/micro.tpl:294
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:294
	qw422016.N().S(`Handler{hdlr}
        return s.Handle(s.NewHandler(&`)
//line examples/protoc-gen-micro/micro.tpl:295
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:295
	qw422016.N().S(`{h}, opts...))
    }

    type `)
//line examples/protoc-gen-micro/micro.tpl:298
	qw422016.E().S(service1)
//line examples/protoc-gen-micro/micro.tpl:298
	qw422016.N().S(`Handler struct {
        `)
//line examples/protoc-gen-micro/micro.tpl:299
	qw422016.E().S(service)
//line examples/protoc-gen-micro/micro.tpl:299
	qw422016.N().S(`Handler
    }

    `)
//line examples/protoc-gen-micro/micro.tpl:302
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:302
		qw422016.N().S(`
        `)
//line examples/protoc-gen-micro/micro.tpl:303
		qw422016.N().S(serviceServer(service, m))
//line examples/protoc-gen-micro/micro.tpl:303
		qw422016.N().S(`
    `)
//line examples/protoc-gen-micro/micro.tpl:304
	}
//line examples/protoc-gen-micro/micro.tpl:304
	qw422016.N().S(`


    `)
//line examples/protoc-gen-micro/micro.tpl:307
	for _, m := range ss.GetMethod() {
//line examples/protoc-gen-micro/micro.tpl:307
		qw422016.N().S(`
        `)
//line examples/protoc-gen-micro/micro.tpl:309
		method, path := m.GetHttpMethod()

//line examples/protoc-gen-micro/micro.tpl:310
		qw422016.N().S(`
        // `)
//line examples/protoc-gen-micro/micro.tpl:311
		qw422016.E().S(method)
//line examples/protoc-gen-micro/micro.tpl:311
		qw422016.N().S(`
        // `)
//line examples/protoc-gen-micro/micro.tpl:312
		qw422016.E().S(path)
//line examples/protoc-gen-micro/micro.tpl:312
		qw422016.N().S(`
    `)
//line examples/protoc-gen-micro/micro.tpl:313
	}
//line examples/protoc-gen-micro/micro.tpl:313
	qw422016.N().S(`
`)
//line examples/protoc-gen-micro/micro.tpl:314
}

//line examples/protoc-gen-micro/micro.tpl:314
func WriteService(qq422016 qtio422016.Writer, ss *gen.Service) {
//line examples/protoc-gen-micro/micro.tpl:314
	qw422016 := qt422016.AcquireWriter(qq422016)
//line examples/protoc-gen-micro/micro.tpl:314
	StreamService(qw422016, ss)
//line examples/protoc-gen-micro/micro.tpl:314
	qt422016.ReleaseWriter(qw422016)
//line examples/protoc-gen-micro/micro.tpl:314
}

//line examples/protoc-gen-micro/micro.tpl:314
func Service(ss *gen.Service) string {
//line examples/protoc-gen-micro/micro.tpl:314
	qb422016 := qt422016.AcquireByteBuffer()
//line examples/protoc-gen-micro/micro.tpl:314
	WriteService(qb422016, ss)
//line examples/protoc-gen-micro/micro.tpl:314
	qs422016 := string(qb422016.B)
//line examples/protoc-gen-micro/micro.tpl:314
	qt422016.ReleaseByteBuffer(qb422016)
//line examples/protoc-gen-micro/micro.tpl:314
	return qs422016
//line examples/protoc-gen-micro/micro.tpl:314
}
