package main

import (
	"github.com/dave/jennifer/jen"
	"github.com/pubgo/xprotogen/gen"
)

func clientMethod(m *gen.Method) *jen.Statement {
	return jen.Id(m.GetName()).
		ParamsFunc(func(group *jen.Group) {
			group.Id("ctx context.Context")
			if !m.GetClientStreaming() {
				group.Id("in *" + m.GetInputType())
			}
			group.Id("opts ...client.CallOption")
		}).
		ParamsFunc(func(group *jen.Group) {
			outType := "*" + m.GetOutputType()
			if m.GetServerStreaming() || m.GetClientStreaming() {
				outType = m.P("{{.srv}}_{{.mthName}}Service")
			}

			group.Id(outType)
			group.Error()
		})
}

func serverMethod(m *gen.Method) *jen.Statement {
	return jen.Id(m.GetName()).ParamsFunc(func(group *jen.Group) {
		group.Id("context.Context")
		if !m.GetClientStreaming() {
			group.Id("*" + m.GetInputType())
		}
		if m.GetServerStreaming() || m.GetClientStreaming() {
			group.Id(m.P("{{.srv}}_{{.mthName}}Stream"))
		}
		if !m.GetClientStreaming() && !m.GetServerStreaming() {
			group.Id("*" + m.GetOutputType())
		}
	}).Error()
}

func serviceClient(m *gen.Method) *jen.Statement {
	j := jen.Id(m.P("func (c *{{.srvS1}})")).Add(clientMethod(m)).BlockFunc(func(group *jen.Group) {
		if !m.GetServerStreaming() && !m.GetClientStreaming() {
			group.Id(m.P(`
			req := c.c.NewRequest(c.name, "{{.srv}}.{{.mthName}}", in)
			out := new({{.outType}})
			err := c.c.Call(ctx, req, out, opts...)
			if err != nil {
				return nil, err
			}
			return out, nil`))
		} else {
			group.Id(m.P(`
			req := c.c.NewRequest(c.name, "{{.srv}}.{{.mthName}}", &{{.inType}}{})
			stream, err := c.c.Stream(ctx, req, opts...)
			if err != nil { return nil, err }`))
			if !m.GetClientStreaming() {
				group.Id("if err := stream.Send(in); err != nil { return nil, err }")
			}
			group.Id(m.P("return {{.srv}}.{{.mthName}}{stream}, nil"))
		}
	})

	j.Line()
	j.Comment("// Stream auxiliary types and methods.")
	j.Id(m.P(`
	type {{.srv}}_{{.mthName}}Service interface {
	   Context() context.Context
	   SendMsg(interface{}) error
	   RecvMsg(interface{}) error
	   Close() error
	{{if .cs}}
		Send(*{{.inType}}) error
	{{end}}

	{{if .ss}}
		Recv(*{{.outType}}) error
	{{end}}
	}`))

	j.Id(m.P(` 
	type {{.srv}}{{.mthName}} struct {
        stream client.Stream
    }

    func (x *{{.srv}}{{.mthName}}) Close() error {
    	return x.stream.Close()
    }

    func (x *{{.srv}}{{.mthName}}) Context() context.Context {
    	return x.stream.Context()
    }

    func (x *{{.srv}}{{.mthName}}) SendMsg(m interface{}) error {
    	return x.stream.Send(m)
    }

    func (x *{{.srv}}{{.mthName}}) RecvMsg(m interface{}) error {
    	return x.stream.Recv(m)
    }

    {{ if .cs }}
        func (x *{{.srv}}{{.mthName}}) Send(m *{{.inType}}) error{
            return x.stream.Send(m)
        }
    {{ end }}

    {{ if .ss }}
        func (x *{{.srv}}{{.mthName}}) Recv() (*{{.outType}}, error) {
            m := new({{.outType}})
            err := x.stream.Recv(m)
            if err != nil {
                return nil, err
            }
			return m, nil
        }

    {{ end }}`))

	return j.Line()
}

func header(fd *gen.FileDescriptor) {
	j := fd.Jen
	j.PackageComment("// Code generated by protoc-gen-micro. DO NOT EDIT.")
	if !fd.GetOptions().GetDeprecated() {
		j.PackageComment("// source: " + fd.GetName())
	} else {
		j.PackageComment("// " + fd.GetName() + " is a deprecated file.")
	}

	j.Id(`
    import (
    	fmt "fmt"
    	math "math"
    	context "context"

		"github.com/pubgo/catdog/catdog_data"

        client "github.com/asim/nitro/v3/client"
    	server "github.com/asim/nitro/v3/server"
    	_ "github.com/gogo/protobuf/gogoproto"
    	proto "github.com/golang/protobuf/proto"
    	_ "google.golang.org/genproto/googleapis/api/annotations"
    )

    // Reference imports to suppress errors if they are not otherwise used.
    var _ = proto.Marshal
    var _ = fmt.Errorf
    var _ = math.Inf

    // This is a compile-time assertion to ensure that this generated file
    // is compatible with the proto package it is being compiled against.
    // A compilation error at this line likely means your copy of the
    // proto package needs to be updated.
    const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

    // Reference imports to suppress errors if they are not otherwise used.
    var _ context.Context
    var _ client.Option
    var _ server.Option`)
}

func serviceServer(m *gen.Method) *jen.Statement {
	m.Set("streamType", m.P("{{.srv1}}{{.mthName}}Stream"))

	return jen.Id(m.P(`
	{{ if and (not .ss) (not .cs) }}
        func (h *{{.srv1}}Handler){{.mthName}}(ctx context.Context, in *{{.inType}}, out *{{.outType}}) error {
    		return h.{{.srvH}}.{{.mthName}}(ctx, in, out)
        }
    {{ else }}
    func (h *{{.srv1}}Handler){{.mthName}}(ctx context.Context, stream server.Stream) error {
        {{ if not .cs }}
            m := new({{.inType}})
            if err := stream.Recv(m); err != nil { return err }
            return h.{{.srvH}}.{{.mthName}}(ctx, m, &{{.streamType}}{stream})
        {{ else }}
            return h.{{.srvH}}.{{.mthName}}(ctx, &{{.streamType}}{stream})
        {{ end }}
    }

    type {{.srv}}_{{.mthName}}Stream interface {
        Context() context.Context
        SendMsg(interface{}) error
        RecvMsg(interface{}) error
        Close() error
        {{ if .ss }}
            Send(*{{.outType}}) error
        {{ end }}

        {{ if .cs }}
            Recv() (*{{.inType}}, error)
        {{ end }}
    }

    type {{.streamType}} struct {
        stream server.Stream
    }


    func (x *{{.streamType}}) Close() error {
    	return x.stream.Close()
    }

    func (x *{{.streamType}}) Context() context.Context {
    	return x.stream.Context()
    }

    func (x *{{.streamType}}) SendMsg(m interface{}) error {
    	return x.stream.Send(m)
    }

    func (x *{{.streamType}}) RecvMsg(m interface{}) error {
    	return x.stream.Recv(m)
    }

    {{ if .ss }}
        func (x *{{.streamType}}) Send(*{{.outType}}) error {
            return x.stream.Send(m)
        }
    {{ end }}

    {{ if .cs }}
        func (x *{{.streamType}}) Recv() (*{{.inType}}, error) {
            m := new({{.inType}})
            if err := x.stream.Recv(m); err != nil { return nil, err }
            return m, nil
        }
    {{ end }}
	{{ end }}`)).Line()
}

func service(ss *gen.Service) {
	ss.Set("srvS", ss.P("{{.srv}}Service"))
	ss.Set("srvH", ss.P("{{.srv}}Handler"))
	ss.Set("srvS1", ss.P("{{.srv1}}Service"))
	ss.Set("srvH1", ss.P("{{.srv1}}Handler"))

	j := ss.Jen
	j.Comment(ss.P("// Client API for {{.srv}} service"))
	j.Id(ss.P("type {{.srvS}} interface")).BlockFunc(func(group *jen.Group) {
		for _, m := range ss.GetMethod() {
			group.Add(clientMethod(m))
		}
	})
	j.Id(ss.P(`
	type {{.srvS1}} struct {
		c    client.Client
		name string
	}
	
	func New{{.srvS}}(name string, c client.Client) {{.srv}}Service {
        return &{{.srv1}}Service{
            c:    c,
            name: name,
        }
    }`))

	for _, m := range ss.GetMethod() {
		j.Add(serviceClient(m))
		j.Line()
	}

	j.Comment(ss.P("// Server API for {{.srv}} service"))
	j.Id(ss.P("type {{.srv}}Handler interface")).BlockFunc(func(group *jen.Group) {
		for _, m := range ss.GetMethod() {
			group.Add(serverMethod(m))
		}
	})

	j.Id(ss.P(
		"func Register{{.srv}}Handler(s server.Server, hdlr {{.srv}}Handler, opts ...server.HandlerOption) error")).BlockFunc(func(group *jen.Group) {
		group.Id(ss.P(
			"type {{.srv1}} interface")).BlockFunc(func(group *jen.Group) {
			for _, m := range ss.GetMethod() {
				if !m.GetServerStreaming() && !m.GetClientStreaming() {
					group.Id(m.P(
						"{{.mthName}}(ctx context.Context,in *{{.inType}},out *{{.outType}}) error"))
					continue
				}

				group.Id(m.P("{{.mthName}}(ctx context.Context,stream server.Stream)error"))
			}
		})

		group.Id(ss.P(`
		type {{.srv}} struct {
            {{.srv1}}
        }
        h := &{{.srv1}}Handler{hdlr}`))

		for _, m := range ss.GetMethod() {
			group.Id(m.P(`catdog_data.Add("{{.pkg}}.Register{{.srv}}.{{.mthName}}",map[string]string{"{{.http_method}}": "{{.http_path}}"})`))
			group.Id(m.P(`opts = append(opts, server.EndpointMetadata("{{.mthName}}", map[string]string{"{{.http_method}}": "{{.http_path}}"}))`))
		}

		group.Id(ss.P(`return s.Handle(s.NewHandler(&{{.srv}}{h}, opts...))`))
	})

	j.Line()
	j.Id(ss.P(`func init() {catdog_data.Add("Register{{.srv}}Handler",Register{{.srv}}Handler)}`))
	j.Id(ss.P(`func init() {catdog_data.Add("Register{{.srv}}",Register{{.srv}}Server)}`))

	j.Id(ss.P(`
	type {{.srv1}}Handler struct {
        {{.srv}}Handler
    }`))

	for _, m := range ss.GetMethod() {
		j.Add(serviceServer(m))
	}
}
